### ISSUE TITLE
PropTypes warning

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#1]
An issue is being printed to the console that reads `Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`. This error is coming from the `react-bootstrap` package that's a dependency of Pup. 

The authors of this package will need to fix this error and release an update. Once they do, we'll upgrade and this error should be removed.

**Comment by sczk** [comment]
The console warning went away for me after switching the PropTypes imports from the 'react' package to the 'prop-types' package in [Authenticated.js](https://github.com/cleverbeagle/pup/blob/b0270cc98b03582c7eb9eaea2a4bd7f08e143541/imports/ui/components/Authenticated/Authenticated.js#L1) and [Public.js](https://github.com/cleverbeagle/pup/blob/b0270cc98b03582c7eb9eaea2a4bd7f08e143541/imports/ui/components/Public/Public.js#L1)

**Comment by cleverbeagle** [comment]
@sczk thanks for pointing this out. Fixed in 1.0.1.
