### ISSUE TITLE
Verify Email workflow seems to cause infinite loop

### ISSUE THREAD

**Issue by julezman** [cleverbeagle/pup#100]
Although I am fairly new to meteor and pup I seem to have found an issue with the verify email workflow.  

**Steps to reproduce:** Worst case: Navigate to the verify email route with and invalid token (i.e. /verify-email/_invalidtoken_).  Other case: It also occurs partly when navigating to a valid email verification token.

**Cause:** When the VerifyEmail component has mounted it calls the Accounts.verifyEmail method which triggers some kind of state change on the server which in turn causes the component to remount causing a loop. In the case of an invalid token this is an infinite loop.

**Symptoms:** Page keeps refreshing, not displaying anything other than Bert alert flashes.  Javascript console shows repeated messages of: "Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the VerifyEmail component".  When a valid token is used the client code eventually triggers a history push to "/documents" and the loop stops.  This does not happen for an invalid token.

**My analysis:** I am not sure if it is some kind of issue with the verifyEmail method within meteor itself (I did try and look through the meteor code and could not see anything that would cause a state change that would trigger a re-render).  Given, I can't find any related issues to this in the wider meteor community, I believe it is something to do with the React/Router setup in pup but my knowledge is lacking in trying to debug this and suggest a fix.  A workaround fix for the valid token side of things is to remove the setTimeout wrapper so it redirects to "/documents" immediately.

Lastly, but most importantly, thanks for creating pup.  It has helped me start to learn meteor and try and put it to some use!  Once I get a bit better I hope to contribute back.

**Comment by cleverbeagle** [comment]
Hi @julezman thank you for the thorough report. I'm having some trouble reproducing per your steps. Here's a GIF of what I'm seeing:

![test-verify-email](https://user-images.githubusercontent.com/23730234/32661887-28e8faa6-c5ee-11e7-956a-e31a504a75b0.gif)


Was your report for a specific browser/OS?

**Comment by julezman** [comment]
Hi @cleverbeagle - Thanks for looking into this so quickly.  I have now discovered what the problem was - a problem on my part.  Sorry for wasting your time.  I had thought I had reverted to the original code I cloned from your repo but it turns out I still had a few pieces of my code there.  The piece of code causing the issue was that in imports/ui/layouts/App.js I had added the loggingIn variable returned from the container creation into a prop and then used this alongside !props.loading to control the rendering of the App.  As a result every time verifyEmail was being called it sets the loggingIn property to true which causes the whole App container to re-render....

Once again, sorry for wasting your time and thanks for the great boiler plate.  Once I get a bit better with the basics and my understanding, I hope to contribute back.  Please let me know how best I can contribute back including unit tests, E2E tests or rather on any of the issues\features\bugs and I will see what I can do.

**Comment by cleverbeagle** [comment]
_HOW DARE YOU_ @julezman.

No worries :) Good to hear you found the fix.
