### ISSUE TITLE
Folder structure with domains/modules

### ISSUE THREAD

**Issue by lorenzogm** [cleverbeagle/pup#101]
Which are your thoughts about creating a folder structure like the one below for the imports?

This way we would have the core of the app (app), everything related with the auth system (auth) and any custom module for our app (documents).

```
| imports
  | app
    | api
    | modules
    | startup
    | ui
  | auth
    | api
    | modules
    | startup
    | ui
  | documents
    | api
    | modules
    | startup
    | ui
```

**Comment by cleverbeagle** [comment]
Hey @lorenzogm. If this make sense to you, go for it :) As far as Pup is concerned, though, we like to keep the structure as close to [the one recommended in the Meteor Guide](https://guide.meteor.com/structure.html).
