### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by vjrj** [cleverbeagle/pup#103]
I'm using pup + i18next + softwarerero:accounts-t9n to make my site multilanguage. Are you interesed in add i18n support to pup? 

Thanks indeed for your work...

**Comment by cleverbeagle** [comment]
Hi @vjrj we'll be releasing a Pro version of Pup in 2018 that will have full support for i18n :)

**Comment by evolross** [comment]
So maybe the Pro version is just every single Pupgrade? Looking forward to it.

**Comment by cleverbeagle** [comment]
@evolross technically, yes, but we'll be adding i18n to Pup 2.0 for free.

**Comment by cleverbeagle** [comment]
Knocking this off 2.0. It's not going to apply to our target demographic and can easily be taught via a tutorial (e.g., "How to Add i18n to Pup").

**Comment by cleverbeagle** [comment]
Changing my mind on this. I've found `react-i18next` to be quite easy to use. Going to add this to 3.0.
