### ISSUE TITLE
Verify email link expired error

### ISSUE THREAD

**Issue by cdolek** [cleverbeagle/pup#107]
"Verify email link expired. Please try again." error shows up when you use the verification link that has been outputted to the console (in development mode after clicking Re-send verification email.)

Tried the link both logged in and logged out. Same thing happens.

**Comment by cleverbeagle** [comment]
Hi @cdolek. This usually happens when additional information is being copied with the url in the console (e.g., the timestamp when the link was logged). Can you run this again and paste the exact URL you're using?

**Comment by cdolek** [comment]
Interesting, I tried the link: http://localhost:3000/verify-email/h2DWgT3vUsW_ssUtDaXNgyFNkUgR7ugj2rwlahd2AMQ and it worked. Not sure what went wrong the first time.

Thanks
