### ISSUE TITLE
Building for mobile got 'Starting app'    till the infinite  

### ISSUE THREAD

**Issue by juanmafont** [cleverbeagle/pup#11]
**(UPDATE--UPDATE)**

**PUP for Mobile**

Note: Previously, I had install: https://dl.google.com/android/repository/tools_r25.2.3-linux.zip android sdk tools, to avoid this issue (linux and mac)
meteor/meteor#8464

**SOLUTION FOR development/debug MODE**

**meteor build ../out_apk  --debug  --verbose   --server=192.168.43.20:3000**
(note: change 192.168.43.20 by your local ip)

Then copy into mobile and can execute it. All Ok.

But if I try without --debug, then I can build  apk, but mobile doesn't install it (says "application damaged". I have the option 'install from unknows origins" activate into my android phone )

  Maybe the problem (I don't know how test that) is when run command: meteor run android-device .....   This meteor command try to install the apk (with not debug option, so this apk is NOT SIGNED) and mobile lock installation..... 

 **SOLUTION FOR production MODE**

 You MUST use 'meteor build' command (not use 'meteor run android-device') and **you must sign your app before upload to the mobile termina**l. (See https://guide.meteor.com/mobile.html#submitting-android)

 Example to got a signed apk:
( Note: The id of apk is com.meteor.examples.pup, that must be set into file **mobile-config.js**)
  ```
 meteor build ../out_apk  --verbose   --server=192.168.43.20:3000
(note: change 192.168.43.20 by your local ip)

 keytool -genkey -alias com.meteor.examples.pup -keyalg RSA -keysize 2048 -validity 10000

 cd ../out_apk
 
 jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 release-unsigned.apk com.meteor.examples.pup

```
Finally, to see SHA1 key (and others keys from signed apk, you need it to configure google oauth services)
```
keytool -exportcert  -list -v
```

Example of file 'mobile-config.js'
```
App.info({
  author: 'cleverbeagle',
  description: 'Testing mobile PUP',
  email: 'none@none.com',
  id: 'com.meteor.examples.pup',
  name: 'test-pup',
  website: 'http://cleverbeagle.com/pup/v1',
  version: '1.0.0',
});
```
 Note:
I think that maybe this is not a issue, but would be good add a 'note',addendum, or tutorial (or add to original tutorial) for users to try compile PUP for mobile.

**(END UPDATE--END UPDATE)**

 ### NOTE:  Below this note is described the older issue when I try  to compile and install PUP for mobile. Above this note, you have the correct way to compile and install PUP for mobile.

Trying to compile PUP for android device will got 'Starting app', but nothing more, nothing happens with mobile. 
 NOTE: Compiling basic Meteor example ( https://github.com/meteor/simple-todos) for mobile is all OK (so I think enviroment is ok for mobile compilation)

Note: I had use: https://dl.google.com/android/repository/tools_r25.2.3-linux.zip  android  sdk tools, to avoid this issue  (linux and mac)
https://github.com/meteor/meteor/issues/8464

 **echo $ANDROID_HOME**
/home/juanma/Android/Sdk

**java -version**
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
**(Note:  Try it also with Oracle SDK, same result :( )**

**ifconfig wlp4s0**
wlp4s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet **192.168.43.20**  netmask 255.255.255.0  broadcast 192.168.43.255
        inet6 fe80::4d22:82cd:365c:ab63  prefixlen 64  scopeid 0x20<link>
        ether ac:b5:7d:b2:ca:61  txqueuelen 1000  (Ethernet)
        RX packets 144317  bytes 199849276 (190.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 50004  bytes 5046455 (4.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**echo $PATH**
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/juanma/Android/Sdk/tools:/home/juanma/Android/Sdk/platform-tools

**cat mobile-config.js** 
App.info({
  author: 'cleverbeagle',
  description: 'Testing mobile PUP',
  email: 'none@none.com',
  id: 'com.meteor.examples.pup',
  name: 'test-pup',
  website: 'http://cleverbeagle.com/pup/v1',
  version: '1.0.0',
});

**meteor add-platform android**
Subproject Path: CordovaLib                  \
android: added platform

**meteor run android-device --settings settings-development.json --mobile-server=192.168.43.20**

=> Started proxy.                             
%% support for subdirectories is deprecated and will be removed in Cordova@7       
Subproject Path: CordovaLibns                [====                     ] 14% 134.6s
Subproject Path: CordovaLibns                [===============           ] 57% 20.5s
                                                                                   
WARNING: It looks like you are using OAuth2 login in your app. Meteor's OAuth2 implementation does not currently work with mobile apps in local
         development mode, except in the iOS simulator. You can run the iOS simulator with 'meteor run ios'. For additional workarounds, see
         https://github.com/meteor/meteor/wiki/OAuth-for-mobile-Meteor-clients.
                                              
WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the local server, make sure your device is on the
         same network, and that the network configuration allows clients to talk to each other (no client isolation).

Starting your app  (Till infinite......... :(  ) 

Here the same, but added --verbose option:
[output_log_pup_verbose.txt](https://github.com/cleverbeagle/pup/files/1094022/output_log_pup_verbose.txt)

**Comment by cleverbeagle** [comment]
@juanmafont it sounds like you were able to resolve this, but I agree, this deserves some documentation. Is the primary issue that the application needs to be signed when built before use locally or uploading to the Play Store?

P.S. Closing this for now but if you can clarify please add an additional comment.
