### ISSUE TITLE
Use the Accounts API to change a user's email address

### ISSUE THREAD

**Issue by ninjaPixel** [cleverbeagle/pup#114]
In `edit-profile.js` we directly update the email address on a user's profile:

```
    Meteor.users.update(userId, {
      $set: {
        'emails.0.address': emailAddress,
        profile,
      },
    });
```

This could lead to us having more than one user with the same email address. I suggest that we use the [Accounts API](https://docs.meteor.com/api/passwords.html#Accounts-addEmail) to do this, as it checks for dupes. We can add an email with:

```
Accounts.addEmail(userId, newEmail, [verified])
```

And, if we want to keep to the structure of only 1 email per user we'd then need to remove the old address with:

```
Accounts.removeEmail(userId, email)
```

**Comment by cleverbeagle** [comment]
Great idea @ninjaPixel. Would you be open to a PR on this?

**Comment by ninjaPixel** [comment]
Sure thing.
