### ISSUE TITLE
documents.insert causes ViewDocument to render without new document ID

### ISSUE THREAD

**Issue by joserocha3** [cleverbeagle/pup#12]
The console throws an error because `doc` is a required prop of `ViewDocument` and the `return` statement setup causes `ViewDocument` to render before the new ID is truly returned. There is a subsequent render after the erroneous one that passing in the `doc` prop so the app still functions. 

I am not enough of an *expert* to know if what I did is the correct fix, but here is it:

**Error in console:**
```
Warning: Failed prop type: The prop `doc` is marked as required in `ViewDocument`, but its value is `undefined`.
```

**Problematic code found in imports/api/Documents/methods.js**
```javascript
'documents.insert': function documentsInsert(doc) {
    check(doc, {
        title: String,
        body: String,
    });

    try {
        return Documents.insert({owner: this.userId, ...doc});
    } catch (exception) {
        throw new Meteor.Error('500', exception);
    }
},
```

**Changing the return statement to this alleviated the issue:**
```javascript
const documentId = Documents.insert({owner: this.userId, ...doc});
return documentId;
```

**Comment by justin88** [comment]
I'm getting the same warning in the console.  This code doesn't solve the issue.

To test, make sure the documents are empty when adding a document.  (Adding a second or third etc document does not trigger the warning.)

**Comment by cleverbeagle** [comment]
Fixed. A simple `doc: Documents.findOne(documentId) || {},` in the container did the trick. The `{}` is enough buffer to not trip the prop type error when transitioning to the ViewDocument page.
