### ISSUE TITLE
Write documentation for redirect after login

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#124]
Whoops. Forgot this.

**Comment by OMFG5716** [comment]
Anyone who comes across, register this onLogin callback with Redirect. Unless Ryan has something better.

```
import { Redirect } from 'react-router-dom';
import { Meteor } from 'meteor/meteor';
import { AccountsCommon } from 'meteor/accounts-base';

AccountsCommon.onLogin(loginDetails => {
  return <Redirect to="/account/dashboard" />
})
```

Cheers

**Comment by OMFG5716** [comment]
Hello! 
Could you please add this on the docs or explain here how to add this?

**Comment by ayhid** [comment]
I might be missing something but I can't find the documentation for after login redirection

**Comment by cleverbeagle** [comment]
Hi @ayhid this is documented here: https://cleverbeagle.com/pup/v2/routing/defining-routes#authenticated-authorized-and-public-routes.

It could use a bit more detail (it's mentioned but not walked through). Do you have a specific question about it?
