### ISSUE TITLE
GraphQL by default

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#125]
Starting to consider this for a few reasons:

1. Less immediate coupling with Meteor.
2. Removes the need to learn Meteor-specific APIs that are rumored to go away.
3. Moves defining schemas directly into the data layer, removing duplication of validation.
4. Opens up Pup to support several databases (and easier for us to provide examples), not just MongoDB.

Thoughts on this @ninjaPixel @merlinpatt @pilarArr? It wouldn't take much work technically to wire it up, however, it would introduce some pretty big paradigm shifts into how we work with folks.

**Comment by ninjaPixel** [comment]
Sounds like fun!

**Comment by toinevk** [comment]
Given with Apollo 2.0, Apollo has introduced its own state management solution and no longer relies on Redux this may be the perfect time.

**Comment by snowzurfer** [comment]
Hey guys, first off thank you so much for making Pup open-source, it's helped me a lot in learning Meteor and React! I've been hearing a lot about Apollo and GraphQL, but I struggle to see how I could adapt what I know about and have with Meteor to use Apollo 2.0. As I have understood, the way Meteor works currently could become obsolete and I'd like to learn the new system as it gets rolled out. Could you pass me some resources on how to do that? Thanks!

**Comment by sw-yx** [comment]
@snowzurfer  honestly GraphQL is one of those things if you don't have a strong idea of why you need it you probably don't need it yet :)

**Comment by cleverbeagle** [comment]
Adding a note: https://www.apollographql.com/docs/react/recipes/meteor

**Comment by cleverbeagle** [comment]
Making a note here for @merlinpatt that I'm using this issue for the branch.

**Comment by cleverbeagle** [comment]
Some things we'll need to document:

- Single query/mutation `.gql` files under `/ui` need to be imported as _default_ exports while multi query/mutation `.gql` files need to be imported as _named_ exports.
