### ISSUE TITLE
MUP Error while deploying 

### ISSUE THREAD

**Issue by RobGordon406** [cleverbeagle/pup#129]
Pup based application works fine in Development.
But when I try to deploy using MUP I get the following error ...

Building App Bundle Locally
Errors prevented bundling:
While processing files with ecmascript (for target web.browser):

/Users/mbp15/MeteorReact/swabfirst/node_modules/babel-plugin-lodash/lib/index.js:105:49:
Cannot read property 'imports' of undefined
at PluginPass.Program

Spent two days trying to discover the issue. 
Just discovered that if I clone a fresh copy of Pup, and try to deploy it - I get the same error.
So it's an issue with MUP and PUP

Any ideas on how to solve this?

**Comment by cleverbeagle** [comment]
This looks like it may be on one of our dependencies, `babel-plugin-lodash`. If I had to guess, when MUP gets to the dependency step, it's getting stuck on installing that package. Out of curiosity, if you delete that package and then try to deploy the app, does it go up without issue?

**Comment by cleverbeagle** [comment]
Hey @RobGordon406 haven't heard back on this so going to close it out. This should be solved in the upcoming 1.5.0 release but if not, feel free to reopen.
