### ISSUE TITLE
For mobile, must add whitelist to show puppy image and load css from external sources

### ISSUE THREAD

**Issue by juanmafont** [cleverbeagle/pup#13]
If you try build for mobile don't forget add whitelist to load external sources need it by Pup.

Example of mobile-config.js:

```
App.info({
  author: 'cleverbeagle',
  description: 'Testing mobile PUP',
  email: 'none@none.com',
  id: 'com.meteor.examples.test_pup_heroku',
  name: 'test-pup',
  website: 'http://cleverbeagle.com/pup/v1',
  version: '1.0.0',
});
// Target Android 4.2 version
App.setPreference('android-targetSdkVersion', '17');
// Whitelist enable access  to img file from amazon
App.accessRule('https://s3-us-west-2.amazonaws.com');
// Whitelist enable access to css file from bootstrapcdn
App.accessRule('https://maxcdn.bootstrapcdn.com');
```

Suppose, you have mondoDB into mlab server and your meteor server app into heroku.
The build command example will be(debug mode):

`MONGO_URL=mongodb://user:password@ds135532.mlab.com:35532/meteor meteor build ../out_apk  --debug --verbose --server=https://test-pup.herokuapp.com`

That command will create a ../out_apk/debug.apk file to install into our mobile phone.

NOTE: change "user" and "password" with your credentials ;) and your target version for Android.

**Comment by cleverbeagle** [comment]
Hi @juanmafont thanks for this. I'm going to close this out but want to keep it around for others who may need the info.
