### ISSUE TITLE
Login attempt rerendering the login.js page ?

### ISSUE THREAD

**Issue by zeiitoun** [cleverbeagle/pup#14]
Is it an expected behavior that a fail attempt to login rerender the login.js page ? 
(Meaning that what you typed dissapear and make the page blink..)

**Comment by cleverbeagle** [comment]
Not sure I understand, can you provide a video of what's happening? Technically speaking, no, the page shouldn't be blinking. If a login attempt fails, you should see a message and remain on the login page until you can successfully login.

**Comment by joserocha3** [comment]
I noticed this as well. It appears that the form submit causes the Public component to recreate the Login component. You do get the Bert alert, but the page completely re-renders which resets the form fields.

**Comment by zeiitoun** [comment]
You do remain on the login page, but react will render the component login another time, loosing any information in the inputs, making the login form dissapearand appear again. (which means for example if you had to scroll to login, you will be back at the top of the page) 

http://imgur.com/a/83EY5

here is a small gif of what's happening. The login wasn't re-rendering in base, that's why I asked the question :)

**Comment by cleverbeagle** [comment]
Ah, I see what you're getting at. I'll take a look :)

**Comment by zeiitoun** [comment]
Caused because the prop **loggingIn** is changing to true during login attempt, making the public component to return a simple <div /> because of this condition in the public component :

`if (loggingIn) return <div />;`
