### ISSUE TITLE
OAuth Callback 

### ISSUE THREAD

**Issue by toinevk** [cleverbeagle/pup#15]
I noted that currently for OAuth the callback function (in OAuthLoginButton) only sends a message during failure and does nothing during success (e.g. push to /documents). Is that intentional or am I missing something obvious? I would've thought it would be desirable to have the OAuth logins/signup consistently show a message / push to /documents as well. 

Thanks, I appreciate the insight.

**Comment by cleverbeagle** [comment]
@toinevk to make sure I understand, when you login via OAuth, are you not being redirected to `/documents`? This is the intended behavior, however, in the case of Pup the redirect for OAuth's isn't handled in the button callback but in the `/imports/ui/components/Public/Public.js` component (it redirects away from public pages to `/documents` if it sees a logged-in user).

**Comment by toinevk** [comment]
I've tried reproducing with a fresh copy of pup but haven't been able to. Must have made a change that was interfering with the public component somehow.  Thanks :)! The boilerplate is great by the way.
