### ISSUE TITLE
oauth.verifyConfiguration doesn't actually verify anything

### ISSUE THREAD

**Issue by Bandit** [cleverbeagle/pup#153]
It just checks if there's an entry for the specified service in the internal Meteor services table, and if so, includes it. Right now even services that don't have an appID or secret set get added to this table, so it does nothing of value.

My proposed solution:

- Add `enabled: true` to each oAuth provider in `settings-development.json`
- Make `oauth.verifyConfiguration` check truthiness of `enabled`

This way people can manually disable oAuth providers which is more flexible (and robust) than just properly checking for a valid secret/appID.

imports/api/OAuth/server/methods.js:
```js
[...]
services.forEach((service) => {
  const serviceObj = ServiceConfiguration.configurations.findOne({ service });
  if (serviceObj && serviceObj.enabled) {
    verifiedServices.push(service);
  }
});
[...]
```

settings-development.json:
```json
{
  "public": {},
  "private": {
    "MAIL_URL": "",
    "OAuth": {
      "facebook": {
        [...]
        "enabled": false
      },
      "google": {
        [...]
        "enabled": true
      },
      "github": {
        [...]
        "enabled": true
      }
    }
  }
}
```

As an aside; since Facebook Login is now requiring even development environments to be run using https, being able to disable oAuth providers is more important than ever.

**Comment by cleverbeagle** [comment]
This is a good point. Going to look at pulling this into the next release.
