### ISSUE TITLE
Import and document usage of onCreateUser hook (in /imports/startup/server/accounts/on-create-user.js)

### ISSUE THREAD

**Issue by firrae** [cleverbeagle/pup#16]
Hey there,

Just moving some of my code from my prototype to this as the base (your login/signup is much nicer than the thing I built!) and I noticed that by default the on-user-create.js file isn't imported anywhere in the base template meaning the code is never actually executed. Not sure if this is meant or not but I didn't see it documented anywhere so I figured I'd mention it.

Maybe I missed it, but hopefully, this helps anyone in the future that puts stuff in there not realising.

**Comment by cleverbeagle** [comment]
@firrae nope, you're right, this is an oversight! I'm struggling to remember, but I think I'd added this as an example of using the `onCreateUser` hook and then forgot to document/import it into `/imports/startup/server/accounts/index.js`.

Good catch :) Going to flag this as a refactor task.

**Comment by firrae** [comment]
That's all I did and it's all good.

**Comment by zerkz** [comment]
Ran into this myself! but figured it out and just imported it.
