### ISSUE TITLE
Can we make SSR toggled via a setting?

### ISSUE THREAD

**Issue by ayhid** [cleverbeagle/pup#163]
Hello,
It's great that pup now supports SSR it's a big step. But how can I disable SSR and keep getting my pup version up to date?

**Comment by cleverbeagle** [comment]
Hey @ayhid! Right now, SSR isn't easily disabled. That said, it shouldn't hurt anything being on. Can you share some more details about why you'd like to disable it? May have a better answer for you...

**Comment by cleverbeagle** [comment]
@merlinpatt @ninjaPixel adding you guys to this so we can put our thoughts together on how we might approach making SSR something that could be turned on/off without much effort.

**Comment by ayhid** [comment]
hey thanks for the quick answer actually I just updated my pup version and I noticed that all my css imports (ie: `import "react-table/react-table.css";`) are now generating errors.

```
/Users/ahidri01/projects/presta-reference/node_modules/react-select/dist/react-select.css:8
W20180529-16:00:48.199(2)? (STDERR) .Select {
W20180529-16:00:48.199(2)? (STDERR) ^
W20180529-16:00:48.199(2)? (STDERR)
W20180529-16:00:48.200(2)? (STDERR) SyntaxError: Unexpected token .
W20180529-16:00:48.200(2)? (STDERR)     at createScript (vm.js:80:10)
W20180529-16:00:48.201(2)? (STDERR)     at Object.runInThisContext (vm.js:139:10)
W20180529-16:00:48.201(2)? (STDERR)     at Module._compile (module.js:616:28)
W20180529-16:00:48.201(2)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20180529-16:00:48.201(2)? (STDERR)     at Module.load (module.js:565:32)
W20180529-16:00:48.202(2)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20180529-16:00:48.202(2)? (STDERR)     at Function.Module._load (module.js:497:3)
W20180529-16:00:48.202(2)? (STDERR)     at Module.require (module.js:596:17)
W20180529-16:00:48.202(2)? (STDERR)     at require (internal/module.js:11:18)
W20180529-16:00:48.203(2)? (STDERR)     at npmRequire (/Users/ahidri01/projects/presta-reference/.meteor/local/build/programs/server/npm-require.js:133:10)
W20180529-16:00:48.203(2)? (STDERR)     at Module.useNode (packages/modules-runtime.js:697:18)
W20180529-16:00:48.203(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:342:20)
W20180529-16:00:48.203(2)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180529-16:00:48.204(2)? (STDERR)     at SelectList.js (imports/ui/components/Forms/SelectList.js:1:512)
W20180529-16:00:48.204(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180529-16:00:48.204(2)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180529-16:00:48.204(2)? (STDERR)     at ProviderForm.js (imports/ui/components/ProviderEditor/ProviderForm.js:1:726)
W20180529-16:00:48.205(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180529-16:00:48.205(2)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180529-16:00:48.205(2)? (STDERR)     at ProviderEditor.js (imports/ui/components/ProviderEditor/ProviderEditor.js:1:485)
W20180529-16:00:48.205(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180529-16:00:48.206(2)? (STDERR)     at require (packages/modules-runtime.js:238:16)
```
it could be another issue completely unrelated to SSR.

The point is in my use case I do not need it as the app will never be public.

I am sur there is another solution with leaving SSR on.

**Comment by ayhid** [comment]
after some googling I added a condition to my import

```
if(Meteor.isClient){
  import "react-table/react-table.css";
}
```

It seems to fix the issue but I don't know if it's the right way to solve this.

**Comment by cleverbeagle** [comment]
Hi @ayhid this is correct. Because all of the app files pass through the server first, this check is required if you're trying to import something intended for the client only.

**Comment by cleverbeagle** [comment]
Just documented the `if (Meteor.isClient)` pattern: https://cleverbeagle.com/pup/v1/the-basics/stylesheets#sass-scss-stylesheets-pup-1-4-0-and-below. 

This doesn't resolve this issue but in case anybody comes across this in the interim!

**Comment by pisacode** [comment]
I am having some issues with the Roles and Subscribtions after upgrading to Pup 1.5 with upstream. I have resolved all conflitcs.However on authentication routes, roles returns false and does not redux does not update the roles. II have a custom Authentication component which checks for additional roles required for routes as the following

`
 <Grid>
          <Switch>
            <Route exact name="index" path="/" component={Index} />
            <Authenticated exact path="/documents" component={DocumentsPage} setAfterLoginPath={setAfterLoginPath} {...props} {...state} />
            <AdminAuthenticated exact path="/editUsers" component={AdminPage} setAfterLoginPath={setAfterLoginPath} {...props} {...state} />
          </Switch>
 </Grid>
`

on AdminAuthenticated page if user does not have the admin role I redirect user to login. After upgrading to ssr path changes back and forth with editUsers and login and then throws 
`Warning: You tried to redirect to the same route you're currently on: "/login"`

Do you have any idea why this might be happening?

**Comment by pisacode** [comment]
Or can I have SSR enabled pages and disabled pages at the same application?

**Comment by cleverbeagle** [comment]
Hey @pisacode, you may want to take a look at v1.6.1 released yesterday. This includes a new `<Authorized />` component which allows you to do what you described. You should be able to copy/paste the component from `/imports/ui/components/Authorized/Authorized.js` and see an example of how to use it in `/imports/ui/layouts/App/App.js`.

Let us know if that works?
