### ISSUE TITLE
Migrate away from imports directory

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#168]
One of the nice parts about Meteor 1.7 is that it now allows us to move away from the imports directory and to specify a `mainModule` to load for the client and server in our `package.json`. While the basic work is fairly trivial, this is going to have a major impact on how we teach and our documentation so we don't want to rush it (it's more of a geeky thing anyways, so not urgent).

**Comment by merlinpatt** [comment]
Doing this feels very much like a public API change for an npm package, which typically requires a major version bump. What do you think about bumping up Pup to v2 once this is done?

**Comment by cleverbeagle** [comment]
@merlinpatt yup, agree. I think that'd be wise.
