### ISSUE TITLE
Refactor profile updates to handle password change on client with Accounts.changePassword()

### ISSUE THREAD

**Issue by zeiitoun** [cleverbeagle/pup#17]
Just saw that the current password retrieved from the form is never used in the profile page. (to modify your password)

Would be interesting to send the hashed password to check it in the meteor call, instead of just overriding it with the new one.

**Comment by cleverbeagle** [comment]
@zeiitoun good catch! The password step should probably be moved to the client so we can leverage this method: https://docs.meteor.com/api/passwords.html#Accounts-changePassword.
