### ISSUE TITLE
The function parseUrlForSSR should not match till it knows which part of the url parts it should use

### ISSUE THREAD

**Issue by pagesrichie** [cleverbeagle/pup#172]
Love the boilerplate, really really helpful when starting new projects!

Noticed one issue and have proposed a fix:

Right now for the following constant in ssr.js:

`const documentURL = parseUrlForSSR(sink.request.url, 'documents');`

The following urls would match:
http://localhost:3000/documents/test/
http://localhost:3000/test/documents/
http://localhost:3000/anything/anything/anythingagain/documents/

While the first should only be the one matching.  In the return parts array, which shows the each piece of the url in its order, it should check which element of the array matches and then only should isMatch be true.

In my code, in order for "http://localhost:3000/documents/test/" to match and not something like "
http://localhost:3000/anything/documents/" I changed the function slightly to look like such:

imports/startup/server/ssr.js:
`const documentURL = parseUrlForSSR(sink.request.url, 'documents', 0);`

where the third argument (in this case '0'), represents the first piece of the url parts.  The parts array in this example looks like such: [ 'documents', 'test' ].  The slight edit to the following function then just checks whether the third argument '0' matches the index of the parts array of the text we sent in the second argument 'documents'.  

imports/modules/parse-url-for-ssr.js:
(Here is a gist of the function code)
https://gist.github.com/pagesrichie/1e18b822346534b6aba6a0e704e29f62

So now http://localhost:3000/anything/documents/ will not run the same match/ssr code that was meant only for http://localhost:3000/documents/anything/ .

Hope you see this fit as including in cleverbeagle's pup's boilerplate code!

**Comment by cleverbeagle** [comment]
Thanks for sharing this, Richie. We'll review for a merge :)
