### ISSUE TITLE
Add robots.txt generator

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#175]
See #174 code for how to do this.

**Comment by merlinpatt** [comment]
From what I'm reading, a `robots.txt` only has two options in it `User-agent` and `Disallow`. What are you thinking should go in here?

http://www.robotstxt.org/robotstxt.html

**Comment by cleverbeagle** [comment]
`User-agent: *` for now should suffice. We just need to make sure we document it so that it's not a surprise for folks.

Makes me think, it may be good to create a "Big Important Things to Know" checklist that's shared as part of the getting started section.

**Comment by merlinpatt** [comment]
Fixed by https://github.com/cleverbeagle/pup/commit/c378211253184966a5738036bde80e9ddad9a8a3
