### ISSUE TITLE
Investigate move to MJML for email templates

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#177]
Came up in another issue and intrigued me. Looks like a nice way to simplify the email templating process (though, forces a creation of templates internally as opposed to on a third-party host—perhaps not a bad thing).

Would be nice to make this a "standard" thing in Pup and help push it forward in the community.

**Comment by merlinpatt** [comment]
While it looks nice, after investigation, this is not worth the move. MJML has no capability for variables. Their reasoning is that it starts with variables, and then people ask for loops, conditionals, etc. While we certainly could do this, it would take away from customer experience to not be able to customize emails.

Additionally, I think that this falls beyond the scope of what we want people to learn using Pup. Our current email templates use HTML, which people know / pick up. MJML, which while similar, would still require learning.
