### ISSUE TITLE
Client side npm package import

### ISSUE THREAD

**Issue by choncj** [cleverbeagle/pup#179]
Firstly thank you for this amazing boilerplate.
Im not used to server side rendering and currently im stuck with a small issue.

Im using a npm package named react-scrollbar which uses the window object.
When trying to import the package i get a warning that window is not defined.

So i tried importing the package like this

```javascript
if (Meteor.isClient) import ScrollArea  from 'react-scrollbar';
```
#163 only issue i found that is kinda related to my problem so i gave it a try but this will tell me that ScrollArea is not defined.

I guess im missing something but i cant find any docs or related posts to my issue.

**Comment by TWKDreamState** [comment]
Hello. How did you fix this as I am having the same issue with Plotly.js?

**Comment by cleverbeagle** [comment]
@TWKDreamState a few ways to handle this. A quick and dirty method is:

```
if (Meteor.isClient) {
  import ScrollArea from 'react-scrollbar';
  window.ScrollArea = ScrollArea;
}

[...]
```

Later in your code you can use `if (Meteor.isClient) window.ScrollArea` and it should work as expected.

Another (preferred) option is to create a module similar to `/imports/modules/validate.js` in Pup. That allows you to handle the client-only import, but also export the variable you need for use in your code.

If you can share the specific code in relation to Plotly.js, happy to take a look and offer some notes :)

**Comment by TWKDreamState** [comment]
Thank you for this :) I'm trying to basically do the following to get started with the Plotly.js library (from the tutorials - https://plot.ly/javascript/react/).

But it causes an error on the server and I just can't seem to work out how to get it working on the client only.

Error: ReferenceError: document is not defined
Code example:

```
import React from 'react';
import Plot from 'react-plotly.js';

class App extends React.Component {
  render() {
    return (
      <Plot
        data={[
          {
            x: [1, 2, 3],
            y: [2, 6, 3],
            type: 'scatter',
            mode: 'lines+points',
            marker: {color: 'red'},
          },
          {type: 'bar', x: [1, 2, 3], y: [2, 5, 3]},
        ]}
        layout={ {width: 320, height: 240, title: 'A Fancy Plot'} }
      />
    );
  }
}
```

**Comment by TWKDreamState** [comment]
OK, got it working thus...but does feel quick and dirty ... :smile: 

`import React from 'react';
import { Meteor } from 'meteor/meteor';
if (Meteor.isClient) {
import Plot from 'react-plotly.js';
  document.Plot = Plot
}
const figure = {
  data: [{
    type: 'scatter',
    x: [1, 2, 3],
    y: [4, 5, 6],
  }],
  layout: {
    title: 'A first initial graph to try out',
  },
};
const Index = () => (
  <div>
    {Meteor.isClient ? (<document.Plot data={figure.data} layout={figure.layout} />) : ''}
  </div>
);

export default Index;`

I couldn't work out how to do it the other way :/

**Comment by cleverbeagle** [comment]
Okay, now that I see what you're up to, what happens if you create `/imports/modules/plotly.js` and write it like this:

```
import { Meteor } from 'meteor/meteor';

if (Meteor.isClient) {
  import Plot from 'react-plotly.js';
  export default Plot;
} else {
  export default () => (<div />); // Blank React component as a precaution to prevent render failure.
}
```

Then in the example above, do...

```
import React from 'react';
import { Meteor } from 'meteor/meteor';
import Plot from '../../../modules/plotly.js';

const figure = {
  data: [{
    type: 'scatter',
    x: [1, 2, 3],
    y: [4, 5, 6],
  }],
  layout: {
    title: 'A first initial graph to try out',
  },
};
const Index = () => (
  <div>
    {Meteor.isClient ? (<Plot data={figure.data} layout={figure.layout} />) : ''}
  </div>
);

export default Index;
```

**Comment by choncj** [comment]
If anybody comes across the same problem while using ScrollArea then simply use the no-css version.

`
import ScrollArea  from 'react-scrollbar/dist/no-css';
`

Then import the css via
```
if(Meteor.isClient) {
	import 'react-scrollbar/dist/css/scrollArea.css';
}
```

**Comment by TWKDreamState** [comment]
Thank you for this - all working now - much appreciated :) Might be useful if anyone else comes across a client only library.

The only issue I had was an error was thrown from the module - Only one default export allowed per module. (7:2) so I removed the 'else' for the time being.
