### ISSUE TITLE
User Settings Modal bug

### ISSUE THREAD

**Issue by choncj** [cleverbeagle/pup#189]
#### Issue description
The User Settings page (/admin/users/settings) has a small bug. 'Add Setting' will not work after clicking on 'Edit'. It will show the form with the previous opened modal Data and it will only give you the option to edit. Only way to clear the form is via page refresh or route change.

#### Steps to reproduce the issue

1. Setup pup
2. Login and go to '/admin/users/settings'
3. Click on Edit 'canSendMarketingEmails' and close via backdrop
4. Click on "Add Setting"

#### What's the expected result?

- Clicking on 'Add Setting' after Editing should show a empty form.

#### What's the actual result?

- Add Setting will now show the old 'canSendMarketingEmails' Form Data.

**Comment by cleverbeagle** [comment]
Thanks for reporting with details @choncj. I'll take a look.

**Comment by choncj** [comment]
Thank you for looking in to this! I also noticed another issue with the modal.

When i want to input something in to the Label field i get this error:

`A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.`

**Comment by cleverbeagle** [comment]
Noted. Thanks @choncj :)
