### ISSUE TITLE
Test out using Chromatic for visual regression testing

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#190]
Would be good to set up a copy of Pup with this and see how it works. A few things to try:

- Add a simple component and break it.
- Break an existing component.
- Take notes on how it could fit into our workflow for Pup/considerations we'd need to make.
- Outline next steps on integrating it into our workflow.

**Comment by ayhid** [comment]
Hi @cleverbeagle  are you talking about [Chromatic](https://blog.hichroma.com/chromatic/home) ?

**Comment by cleverbeagle** [comment]
@ayhid yup!

**Comment by merlinpatt** [comment]
Relevant links

* [The original repo, now deprecated](https://github.com/meteor/chromatic)
* [The new QA tool](https://www.chromaticqa.com/)

**Comment by merlinpatt** [comment]
Chromatic relies on Storybook, and since we've decided against including Storybook by default, we won't be able to have Chromatic by default as well, so I'm closing this. However, for those interested, we'll post a write up about how to add Storybook and Chromatic to Pup.
