### ISSUE TITLE
Breadcrumb link bug

### ISSUE THREAD

**Issue by w3jimmy** [cleverbeagle/pup#191]
Hi, there is a small bug in the edit User admin view, in the Breadcrumb generation.
Once you click on one user to open its details, an error shows in the client's console:

```Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.```

To fix this, I've changed it this way:

```
import { LinkContainer } from 'react-router-bootstrap';

...

<Breadcrumb>
      <LinkContainer to="/admin/users">
            <Breadcrumb.Item>Users</Breadcrumb.Item>
      </LinkContainer>
...
```

I hope this recommendation is the best.
Keep up the good work!
Thanks

**Comment by cleverbeagle** [comment]
Thanks for the heads up @w3jimmy!
