### ISSUE TITLE
Add ability to manage roles via admin UI

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#193]
Just came up on the forums and I *think* some starter code exists in an earlier fork of Pup.

**Comment by merlinpatt** [comment]
Started this on [this branch](https://github.com/cleverbeagle/pup/tree/feature/admin-roles). The roles display on the user list. For actual management, what do you think about a button that turns into a multi select dropdown?

**Comment by cleverbeagle** [comment]
Acknowledging this. Let me take a peek tomorrow and follow up .

**Comment by cleverbeagle** [comment]
@auBusinessDaD can you share some more info about what you're asking? There's this component in React Bootstrap that may be of interest: https://react-bootstrap.github.io/components/dropdowns/#btn-dropdowns-split

**Comment by auBusinessDaD** [comment]
Thanks @cleverbeagle, I was following on from @merlinpatt's idea to display the current value (or assigned role) and then have the button to edit it change into the select.
I have been thinking about this this week and i am not sure that would work best if we did multi-select for roles.

**Comment by ayhid** [comment]
I can work on this, actually I'll be implementing this for a project at work where I am using pup.
@cleverbeagle have you started working on this yet ?

**Comment by cleverbeagle** [comment]
@ayhid I haven't feel free to give it a spin.
