### ISSUE TITLE
updating to jquery@3.3.1 breaks bootstrap

### ISSUE THREAD

**Issue by Salamit** [cleverbeagle/pup#194]
Because of a vulnerability with jquery that comes with the boilerplate, and following suggestions by npm audit, I had to upgrade to jquery

But I now I get the following in the console. 
`twbs_bootstrap.js?hash=9ce2be5568dddbf86b5c6732b75ce4a038d39c56:42 Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3`

Any tips? I'm considering removing bootstrap.

**Comment by cleverbeagle** [comment]
Unfortunately this will be unfixable until we can upgrade to v4 of Bootstrap (currently blocked by our dependency on `react-bootstrap`). Keep an eye on [this issue](#122) for updates.

**Comment by pisacode** [comment]
Hi. which version should we use until this problem is fixed?

**Comment by cleverbeagle** [comment]
@pisacode the one that's bundled with Pup by default (`2.2.4`) is best.

**Comment by pisacode** [comment]
Hi, thank you very much for fast response.

I am have followed your suggestion on #181 and run `npm audit fix`. But now validate module is giving an error as the following:`TypeError: $(...).validate is not a function` 
It seems like jguery is not installed properly. 

I have also run `npm install --save jquery@2.2.4` to save but no luck. 

Do you have any suggestions?

**Comment by pisacode** [comment]
It works if I don't do the `npm audit fix`. And also #178 shows that there is something that I am missing. Usually this happens when you import jquery twice, but I guess it is not the case here

**Comment by pisacode** [comment]
I have get it working by doind a `npm audit` and then selectively fixing problems, leaving jquery out. `npm audit` says there are around 150 vulnerabilities however most of the get solved by just 4-5 commands.

**Comment by Salamit** [comment]
@pisacode, I’m getting the same issue now

**Comment by pisacode** [comment]
Did you try to selective fix issues on the `npm audit` ?

**Comment by Salamit** [comment]
@pisacode sorry that this is late. I stepped away from pup for a bit. I will try as you suggested. I do want to get rid of jquery. Any luck on your end?

**Comment by Salamit** [comment]
@pisacode I found a work around the specific issue of `Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3`

Simply include this in at the top of your main.html file
```
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
```
Source: https://react-bootstrap.github.io/getting-started/introduction/

This is now an issue of the form validator not working.

**Comment by cleverbeagle** [comment]
@Salamit thanks for sharing notes. This is on our radar but will require moving around some other parts in use in the framework like you noted.
