### ISSUE TITLE
Problem with heroku deploy

### ISSUE THREAD

**Issue by akwilos** [cleverbeagle/pup#197]
Hello, 
I try to deploy pup app on heroku based on:
https://github.com/jordansissel/heroku-buildpack-meteor

After deploy, which was success, on web page I see appliction error.
In logs i cant see any problematic issue.
@cleverbeagle Could you try help me, please?

**Comment by merlinpatt** [comment]
@akwilos I've always used the horse buildpack to great success. Try this instead.

* Set buildpack to: https://github.com/AdmitHub/meteor-buildpack-horse.git 
* Add env vars
  * `MAIL_URL` - can be blank
  * `METEOR_SETTINGS` - set to at least an empty object `{}` 
  * `MONGO_URL` - format should be `mongodb://username:password@host:port/database`
  * `ROOT_URL` - either your custom domain or your Heroku app URL
* Redeploy

For debugging, run the command `heroku logs --app app-name --source app`. This will always output logs from the app and not a bunch of Heroku nonsense.

Let me know if that works. If not, post your logs here.

**Comment by akwilos** [comment]
i have seen in logs:

> TypeError: Cannot read property 'supportEmail' of undefined

but in settings.json i can see it

`  "private": {
    "MAIL_URL": "smtps://...@smtp.gmail.com:465",
    "OAuth": {
      "facebook": {
...
      },
      "google": {
...
      },
      "github": {
...
      }
    },
    "supportEmail": "Customer Support <support@product.com>"
  },`

**Comment by akwilos** [comment]
Ok i fixed it.
I copy all things from settings.json to METEOR_SETTINGS in heroku.com
Thank all
