### ISSUE TITLE
Did not expect server HTML to contain a <nav> in <div>

### ISSUE THREAD

**Issue by pisacode** [cleverbeagle/pup#199]
I am having this issue when hydrate runs at start-up. It normally resolves when you eliminate whitespace in rendering node. However I couldn't fixed it with the solutions mentioned in [here](https://github.com/facebook/react/issues/10879)

Any idea to fix it?

**Comment by cleverbeagle** [comment]
Hey @pisacode can you screenshot/paste the exact error you're getting?

**Comment by pisacode** [comment]
Sure,

This is the error message:
![screen shot 2018-08-07 at 10 13 21 am](https://user-images.githubusercontent.com/9843437/43760490-e2b19b12-9a2a-11e8-8661-12e84d294ae0.png)


This is where it is originated:
`Meteor.startup(() => hydrate(<ThemeProvider theme={theme}>
<Provider store={store}>
  <BrowserRouter>
    <Switch>
      <App />
     </Switch>
    </BrowserRouter>
 </Provider>
</ThemeProvider>, 
document.getElementById('react-root')));`

And the only place that has a nav under div is the  `AuthenticatedNavigation.js` component

**Comment by sayjeyhi** [comment]
In my case it was because of using `PersistGate` and `react-loadable`. if you using this libraries, you could use preloadAll instead of preloadReady
