### ISSUE TITLE
Documentation Display Errors.

### ISSUE THREAD

**Issue by isaac-martin** [cleverbeagle/pup#202]
Some errors with Documentation styling. Not sure if this is on git anywhere, but if it is I can open a PR?

```
.Documentation .DocumentationCode pre+.CodeBlock-footer {
    margin-top: -32px;
}
```

This negative margin means the footers overlap the code.

**Comment by cleverbeagle** [comment]
@isaac-martin can you link me up to where this is overlapping the code?

**Comment by isaac-martin** [comment]
Sorry should have done that originally 
https://cleverbeagle.com/pup/v1/getting-started

![screen shot 2018-08-06 at 2 38 25 pm](https://user-images.githubusercontent.com/8649366/43734668-726b1454-9986-11e8-89a4-0df37e998c4b.png)

**Comment by cleverbeagle** [comment]
Ah, got it. I think this was a goof due to our recent redesign. I'll take a look.

**Comment by cleverbeagle** [comment]
Fixed 🎉
