### ISSUE TITLE
Improve security with browser-policy package

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#208]
This used to be in Base before it became Pup. It was an oversight leaving it out and I just realized it was never added back in :|

We can go back to the old Base repo and pull the rules from there (and review them for accuracy): https://github.com/themeteorchef/base/blob/master/imports/startup/server/browser-policy.js

https://themeteorchef.com/tutorials/using-the-browser-policy-package

**Comment by cleverbeagle** [comment]
Update blog post on security when this is complete.

**Comment by cleverbeagle** [comment]
https://www.npmjs.com/package/sanitize-html

**Comment by merlinpatt** [comment]
I've added browser-policy in on [this commit](https://github.com/cleverbeagle/pup/commit/afe0f56c34250fe874ec86fac135c4bb7d0c993f).

Where do we need input sanitization? We're not displaying any user's input as raw HTML.
