### ISSUE TITLE
Add webhooks

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#211]
We should include some example patterns for handling webhooks. They're common enough to most products that it wouldn't hurt to have them.

**Comment by auBusinessDaD** [comment]
Hey guys, happy to help where I can - but an idea for an example here could be a post webhook, so as an admin I can send out a notification to all users of something - e.g. a notification like "we are performing an upgrade, expect performance delays" ?? or something less dramatic like "we have a new feature or special" ??
