### ISSUE TITLE
Can't import images and icons.

### ISSUE THREAD

**Issue by akwilos** [cleverbeagle/pup#212]
Hello.
I have a problem with loading the images and icon.
What is the best and appropriate way to loading a data in pup app?

In addition, i have seen we have a two type app on master and on 2.0.0 It is possible to merge all new commits merged to master also to branch 2.0.0 Now i have seen one commits (with update history) not exsist in 2.0.0 branch

Thanks

**Comment by MateoWartelle** [comment]
I am sorry I don't quite understand the question.  Maybe an example would be better to get to a resolution. 

#### Images
```
<img src="PATH/TO/FILE" alt="Some Image" />
```
#### Icons
```
<i className="fa fa-star" />

**Comment by akwilos** [comment]
Thanks @MateoWartelle 
but in which folder should I put my images? in public or another?
and do you know any svg sprite packages for pup boilerplate.
I used a few the most popular packages and it doesn't work.

**Comment by merlinpatt** [comment]
Your images need to go in public.

What sprite packages are you using?

**Comment by akwilos** [comment]
this one: https://www.npmjs.com/package/react-svg-icons

And i see in my chrome console:
`Uncaught TypeError: FS.readFileSync is not a function`

**Comment by cleverbeagle** [comment]
@akwilos if you're getting that error, than that package is expecting to be run in a server environment. `fs.readFileSync()` is not available on the client.

**Comment by akwilos** [comment]
@cleverbeagle thank you. Its a package for react  which i use in the past. So what is a problem in meteor app? 
Anyway, Do you know any packages for svg sprite, which will be work in our pup boilerplate?
