### ISSUE TITLE
Restructure components 

### ISSUE THREAD

**Issue by jesperordrup** [cleverbeagle/pup#215]
And maybe even subfolders.

To keep a clear picture of which components is available for a certain area I find it easier if they are named as this:

Pages/Documents/DocumentEdit
Pages/Documents/DocumentView
Pages/Documents/DocumentList
Components/Navigation/NavigationPublic
Components/Navigation/NavigationAuthenticated

The current naming makes it difficult to see "what you have".

**Comment by ArchiCroc** [comment]
I agree, I'm kicking off a new project that will have a lot modules.

To help keep mine organized I've refactored pup all the pup pages into subfolders for  each modules with a components folder for the components unique to those pages like-

imports/ui/{{module}}
imports/ui/{{module}}/components 

So imports look like this:

imports/ui/admin- for admin pages
imports/ui/components - for common components
imports/ui/documents - for the documents module
imports/ui/layouts - for the layouts
imports/ui/pages - for the static pages
imports/ui/users- for the user account pages
imports/ui/{{myCustomModule1}}
imports/ui/{{myCustomModule2}}

If there is interest in this, I'll make a pull request.

**Comment by cleverbeagle** [comment]
Hey @ArchiCroc, this has been decided for 2.0. Happy to link to a fork that follows this pattern, or, do a guest post on the blog about the advantages of using this pattern.
