### ISSUE TITLE
Feature: Slack integration

### ISSUE THREAD

**Issue by jesperordrup** [cleverbeagle/pup#216]
It would be a great example on how to integrate using webhooks and exposing an endpoint.

Example 

- Posting to slack channel when document collection is changed.  
- Slash command to list documents, add comments

**Comment by cleverbeagle** [comment]
This is an interesting one. We do have an open issue for adding webhooks (#211) examples to Pup, but for receiving from not sending to third-party apps. This one would be best done as a Pupgrade (adding it to our list).
