### ISSUE TITLE
We can do better with documents

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#220]
The documents feature is leaving something to be desired. I think we can do better. It'd be neat if it was like an actual document editor...like a simple Markdown sort of thing with a preview.

Would be a good learning tool for folks and really improve the overall quality of the app.

**Comment by cleverbeagle** [comment]
This is starting to come together in mind. It'd be neat to add comments to documents (this came up in an older issue from a mentee suggestion) so that we can demonstrate nested fields in GraphQL.

**Comment by merlinpatt** [comment]
Started this on [doc-comments branch](https://github.com/cleverbeagle/pup/tree/feature/doc-comments). I think we should separate out the GraphQL resolvers and types to each API folder (`Documents/resolvers`, `Documents/types`, etc). For a more complex app, these files could end up obscenely large. Thoughts?

**Comment by cleverbeagle** [comment]
@merlinpatt 100% agree.

**Comment by cleverbeagle** [comment]
Realizing our implementation is kind of booty. Right now the logic is your /documents list is private and limited to you, the current user, while ALL of your documents are instantly public (to demonstrate SSR). This should be toggleable so folks can decide which documents are public (and SSR) vs. which are obscured.

**Comment by cleverbeagle** [comment]
This is good to go!
