### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#229]
The rewrite of the Documents feature is ready to go but it'd be good to spend some more time with comments. @merlinpatt suggested we move this to a 2.1+ release which makes sense. We can use this as a way to showcase subscriptions in GraphQL (the wiring is there on the server but we need a client side example).

**Comment by auBusinessDaD** [comment]
What is your release cycle? i.e. V2 and then incrementally from there?
