### ISSUE TITLE
Required object in pages retrieving from database throw a warning

### ISSUE THREAD

**Issue by zeiitoun** [cleverbeagle/pup#23]
Currently, when you try to access a document by typing random id (localhost:3000/documents/sdqlifhqsdhlfh/edit) for example, you will get this warning :

> printer.js:170 Warning: Failed prop type: The prop `doc` is marked as required in `EditDocument`, but its value is `undefined`.
>     in EditDocument (created by ReactMeteorDataComponent)
>     in ReactMeteorDataComponent (created by Route)
>     in Route (created by Authenticated)
>     in Authenticated (created by App)
>     in Switch (created by App)
>     in div (created by Grid)
>     in Grid (created by App)
>     in div (created by App)
>     in Router (created by BrowserRouter)
>     in BrowserRouter (created by App)
>     in App (created by ReactMeteorDataComponent)
>     in ReactMeteorDataComponent

(Removing the required type of the proptypes and setting a default value would fix it ? is it the cleanest way ?)

**Comment by cleverbeagle** [comment]
Hmm. This is the intended behavior, but for the sake of cleanliness you're right. Off-hand this should be handled via the default value.
