### ISSUE TITLE
Add tutorials to /pup landing page

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#231]
The most obvious question when someone first finds Pup is "how do I use this?" This can easily be answered by adding a set of tutorials to the /pup landing page that map back to our blog.

**Comment by auBusinessDaD** [comment]
Oooh, this i can actually help with without getting in the way! Want me to take it fellas?

**Comment by cleverbeagle** [comment]
Hey @auBusinessDaD this is for our site at https://cleverbeagle.com/pup so we'll be handling this one internally. Do you have any experience with CraftCMS/PHP by any chance, though?

**Comment by auBusinessDaD** [comment]
Ahhh, I thought this was to do with the boiler plate 'default' home page that comes up when you first clone.

I have experience with CraftCMS/PHP, but am not an expert.

**Comment by cleverbeagle** [comment]
@auBusinessDaD okay, can you send an email to ryan.glover@cleverbeagle.com? May be a freelance opportunity here.

**Comment by auBusinessDaD** [comment]
Email just sent
