### ISSUE TITLE
Add "Built with Pup" section to /pup

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#232]
A common question we get is "what has Pup been used to build?" It'd be good to have a showcase of these projects (whether from mentees, folks in the community, or ourselves) so people can see what's possible.

**Comment by auBusinessDaD** [comment]
Meteor do this to some effect and i do agree, probably more something for the pup discussion forum though? We would need developers to get in touch though.

From GitHub view though, this could be great on the app home page? Maybe merge this issue with that?

**Comment by cleverbeagle** [comment]
Hey @auBusinessDaD that's a good idea. Would you be willing to start a thread on the forum for us (something like "Are you building with Pup? We want to add you to our showcase!")?

Can you clarify the other issue you're talking about? This one is just for us internally so we know about the work to be done.
