### ISSUE TITLE
Can we utilize Docz?

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#238]
Came across this in a tweet: https://www.docz.site/.

Looks like it may save us some fuss with our own docs.

**Comment by meteorplus** [comment]
wow so sick

that's so good

**Comment by merlinpatt** [comment]
Played around with this. While docz will work with basic components, any components that import Meteor packages won't work. Unless we can document using one tool, we shouldn't switch to a different tool.
