### ISSUE TITLE
Remove fetchMethodNames method in /imports/modules/rate-limit.js

### ISSUE THREAD

**Issue by zeiitoun** [cleverbeagle/pup#24]
You can directly access the methods name by using the property methods : 

name(name) { return _.contains(methods, name); },

**Comment by cleverbeagle** [comment]
Can you provide more detail here? I don't see where the `methods` property is coming in from your example...

**Comment by zeiitoun** [comment]
Directly from the assignLimits constant. 

```
const assignLimits = ({ methods, limit, timeRange }) => {
  if (Meteor.isServer) {
    DDPRateLimiter.addRule({
      name(name) { return _.contains(methods, name); },
      connectionId() { return true; },
    }, limit, timeRange);
  }
};
```

This is not working : (no need to fetch the method names, it's already there)

`const methodNames = fetchMethodNames(methods);`
