### ISSUE TITLE
Document ESLint usage and configuration

### ISSUE THREAD

**Issue by pilarArr** [cleverbeagle/pup#25]
I'm not sure if this goes here, but this link (http://cleverbeagle.com/pup/v1/the-basics/linting) is not working.
It's located in File Structure, on the paragraph on `package.json`

**Comment by cleverbeagle** [comment]
Hi @pilarArr this is the correct spot. I intended to do a section on linting but left it out for now so this link shouldn't be here. Just corrected this.

Side note: if you're curious about linting and how it works in Pup, let me know and I can bump this up in the list of things to expand on.

**Comment by pilarArr** [comment]
Hi @cleverbeagle, 

I am curious about linting, I've started linting recently. I've tried different linters and I wanted to use esLint but it looked too advanced for me. The configuration that you have in pup works perfectly for me so I can finally use esLint. I've been reading stuff and I wanted to see what you had to say about it so an article on linting would be nice, your docs on pup are amazingly good.

But I'd rather see how you implement email verification or a basic user manager first 😄 
Awesome work btw, thanks for sharing 🥇

**Comment by cleverbeagle** [comment]
@pilarArr got it. I'll convert this issue to remind me to write something on linting.

Re: email verification, you're in luck as this is coming in the 1.1.0 release that I'm working on this morning. User management is in the works, too, but for a pro version of Pup coming out later this year.
