### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#252]
This keeps coming up and it'd be good to standardize. Right now in Pup, errors are simply logged to either the client or server console. This is fine in dev, but it'd be good if there was an easy convention for hooking in Slack or another service.

This may be best done as a Pupgrade (some folks may not want to output to a logging service), but this feels like a good free thing.

**Comment by evolross** [comment]
It could be a good idea to show an example or have the pupgrade show how to send Galaxy's logs to a custom logging solution (e.g. ElasticSearch).  [There's a way to do this](https://galaxy-guide.meteor.com/logs.html).

**Comment by cleverbeagle** [comment]
@evolross I'll take a look, but I'll only do it if Dirk Diggler approves.
