### ISSUE TITLE
Add unit test for Validation component

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#253]
Need to ensure that the component validates the `children` prop correctly. Would be a good opportunity to showcase unit testing with Jest and Enzyme.

**Comment by wei170** [comment]
Hi,
Do we have any update on this? I have some errors in importing gql files to react component. For example,
```
Invariant Violation: Argument of [object Object] passed to parser was not a valid GraphQL DocumentNode. You may need to use 'graphql-tag' or another method to convert your operation into a document
```

Thank you

**Comment by cleverbeagle** [comment]
@wei170 your GraphQL problem seems unrelated. Are you having trouble with the `<Validation />` component?

**Comment by wei170** [comment]
I do have another problem with the Validation component about `import`.

**Comment by wei170** [comment]
I have the following error:
![image](https://user-images.githubusercontent.com/13220740/53124006-573b9f80-3528-11e9-9411-4e99ce8e4975.png)

**Comment by cleverbeagle** [comment]
@wei170 can you share your test file you're trying to run?
