### ISSUE TITLE
Migrate Meteor accounts to use GraphQL

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#254]
Right now this is dependent on a `withTracker` container on our `<App />` component. Because the only thing that really needs the user at that level is our routing, it may be worth experimenting with a HOC or the Context API to see if we can isolate just to the components that need it.

**Comment by merlinpatt** [comment]
I think the Context API is the way to go. We can get the info at the top level, put it in a UserData context provider, and then lower levels can get it as needed.

I think the main issue surrounding auth is how to handle users who logged in, left, and came back. 

For new sign ups or folks who log out and come back, it's easy. They get shown the log in / sign up page. We do the back end stuff and pass it back to the front.

But for those who stay logged in, there's the issue where it will show the logged page for a bit, then log them in and suddenly switch, which is disconcerting even if you expect it. So how do we handle this case?

**Comment by cleverbeagle** [comment]
@merlinpatt we can just do what we do now and rely on the `Meteor.loggingIn()` prop to tell us whether or not we should expect a user to be present. If logging in, we won't render anything, if not, we'll check to see whether we have a user and route accordingly.

**Comment by SachaG** [comment]
Are you guys rolling out your own GraphQL account solution? Or maybe using something like https://github.com/flyblackbird/apollo-accounts
