### ISSUE TITLE
Rename button "Share" To "Post Comment"

### ISSUE THREAD

**Issue by jesperordrup** [cleverbeagle/pup#261]
When viewing the document you can post a comment. I suggest renaming the button "Share" To "Post Comment" as it is more clear what exactly will happen.

**Comment by ayhid** [comment]
it's an easy pick if no PR already exists for this I can do it.

**Comment by cleverbeagle** [comment]
Sure, that'd be a big help! I'm looking to do a release this coming Monday (6/24).
