### ISSUE TITLE
Add ability to sort comments by newest or oldest

### ISSUE THREAD

**Issue by jesperordrup** [cleverbeagle/pup#263]
When viewing the document list the comments in reverse date order (newest top). When posting a new comment this also makes it easier to see your posted comment.

**Comment by cleverbeagle** [comment]
Going to rethink this one. Most comment systems put your comment at the bottom (in order it was posted). We could utilize subscriptions to put this at the top and highlight it as "your comment" and then on refresh, it moves to bottom as expected.

**Comment by wortkotze** [comment]
proposal: make it configurable in the user config
we have such a cool way to add user preferences :) - we could use it
