### ISSUE TITLE
Improve users search/sensitivity in admin

### ISSUE THREAD

**Issue by jesperordrup** [cleverbeagle/pup#264]
Go to admin/users
type user+23

Expected: 1 hit
Result: 0 hits

Workaround:
Edit and save user. Then search works.

**Comment by cleverbeagle** [comment]
Going to call this an improve. MongoDB's regex search is ignoring the + so we need to factor that in.

**Comment by cleverbeagle** [comment]
This will be better handled by #316. Closing this one out.
