### ISSUE TITLE
Document using a hardcoded local URL

### ISSUE THREAD

**Issue by rlhk** [cleverbeagle/pup#271]
Developing on the default config with localhost:3000 is fine.

However when I tried to test the local dev version from a device in the local network, say 192.169.110.1:3000, one of the client requests is still pointing to localhost:3000. Specifically, it's `http://localhost:3000/__meteor__/dynamic-import/fetch`, which makes the app unresponsive/unable to login from devices other than localhost.

Where to fix the issue?

**Comment by cleverbeagle** [comment]
Hi @rlhk. Good question. That's not a URL that Pup configures directly—you'd need to change the URL of the app directly on startup. You can do this with the following in your terminal:

```
meteor npm start --port 192.168.110.1:3000
```

or

```
meteor --port 192.168.110.1:3000 --settings settings-development.json
```

**Comment by rlhk** [comment]
Cool that works. Is this a potential issue that should be fixed at Meteor side?

**Comment by rlhk** [comment]
mm... I found that I need to hardcode my intended IP & port in `settings-development.json` like so:

```
{
  "public": {
    "graphQL": {
      "httpUri": "http://192.168.110.1:3000/graphql",
      "wsUri": "ws://192.168.110.1:4001/graphql"
    },

```

Otherwise I'll have Apollo errors:
```
E20181119-16:26:04.483(8) (webapp_server.js:991) Error running template: Error: Network error: request to http://localhost:3000/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:3000
    at new ApolloError (/Users/roger/dev/innonation/musejam4/node_modules/apollo-client/bundle.umd.js:85:32)
    at /Users/roger/dev/innonation/musejam4/node_modules/apollo-client/bundle.umd.js:1039:45
...
```

**Comment by rlhk** [comment]
Hi @cleverbeagle I think the main issue could be regarded as resolved.
However I'm wondering if you like the idea of overriding the Uris defined in `settings-development.json` when custom Uri is provided. Would love to submit a PR for that.

**Comment by cleverbeagle** [comment]
@rlhk I'd like to avoid that as it's a specific use case that doesn't come up very often (I think you're the first to ask ever). I'd be open to adding something to the docs, though, or doing a guest post on the blog showing how to do it.
