### ISSUE TITLE
Show the graphql powers on documents list

### ISSUE THREAD

**Issue by jesperordrup** [cleverbeagle/pup#272]
Add comments count to the list of documents to show the true power of graphql. 

The example should show how to do a calc on comments

{documents {
   title
   _id
   commentCount
}}

I assume that Query type would require a new field to be added 'commentCount' which should be resolved somehow?

I did try - no luck :)

**Comment by cleverbeagle** [comment]
What does your resolver function look like?

**Comment by jesperordrup** [comment]
I added the commentCount field to the Type:

`export default 
  type Document {
    _id: String
    isPublic: Boolean
    title: String
    createdAt: String
    updatedAt: String
    body: String
    owner: String
    comments: [Comment]
    commentsCount: Int
  }
;`

First thought was to add logic to the existing resolver for documents (api/Documents/queries.js)

` documents: (parent, args, context) `

I thought that the field commentCount I added to the Type would show as an arg or in context allowing me to decide when to count and return the comments. I gave up on that since I couldnt find any info. 

Next thing I tried was to add the field as a resolver itself. But I didnt find any. 

While writing this I just thought of changing the type of the variable in the type:

`export default 
  type Document {
    _id: String
    isPublic: Boolean
    title: String
    createdAt: String
    updatedAt: String
    body: String
    owner: String
    comments: [Comment]
    commentsCount: doCountTheComments
  }
;`

and then add a resolver for doCountTheComments. Is that the direction?

**Comment by jesperordrup** [comment]
I made it work in this example. The query for authors counts number of posts.:
https://launchpad.graphql.com/ln5x3vqqwq

So I tried the same - heres the type:

`export default 
  type Document {
    _id: String
    isPublic: Boolean
    title: String
    createdAt: String
    updatedAt: String
    body: String
    owner: String
    comments: [Comment]
    commentsCount: Int
  }
;
`

And the resolver:

`export default {
  comments: ({ _id }) =>
    Comments.find({ documentId: _id }, { sort: { createdAt: 1 } }).fetch(),
  commentsCount: ({ _id }) =>
    Comments.find({ documentId: _id }, { sort: { createdAt: 1 } }).fetch().length,
};
`

This should allow me to query:

`{
  documents {
    
    title
    commentsCount
  
  }
}`

But commentsCount is always 0 
(no errors in console)

**Comment by jesperordrup** [comment]
SOLVED

Forgot to add the object structure to the resolver object (in api.js)

   Document: {
      comments: CommentQueries.comments,
      commentsCount: CommentQueries.commentsCount,
    },
