### ISSUE TITLE
Fix email verification being displayed for OAuth logins and re-verify new email address when updating in profile

### ISSUE THREAD

**Issue by pilarArr** [cleverbeagle/pup#28]
I noticed that when you change the email in the profile page, it doesn't prompt you to verify that email since it only changes the address field and the verified stays true.

Also when you log in with Facebook or Google. It prompts you send a verification email to an empty field. I'm not sure what would be the way around that. If assuming the email if already verified by Facebook or re check the verification.

**Comment by cleverbeagle** [comment]
Good catches @pilarArr! Hadn't even considered how OAuth would treat this. Going to flag this as a bug and patch soon.
