### ISSUE TITLE
Bug deployment on heroku

### ISSUE THREAD

**Issue by TroubadourFabiolas** [cleverbeagle/pup#281]
Hi,

**1) In the first time,** when I deployed the origin code to heroku server with git clone https://github.com/cleverbeagle/pup <my-project-name>

The launching application didn't work.

I managed to correct this with to copy the content of 'settings-development.json' file and paste in Heroku => myProject => Setttings => Reveal Config Vars => Key : METEOR_SETTINGS and Value : I pasted here the content.

thanks to :
- https://github.com/cleverbeagle/pup/issues/9
- https://github.com/cleverbeagle/pup/issues/197

So, now, the app is showing on server.

**2) On Chrome console, I have this error :** 

> `50d72c91808ef7fba57f920b67d152d2d57698eb.js?meteor_js_resource=true:9 WebSocket connection to 'ws://localhost:4001/graphql' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

so I changed this in METEOR_SETTINGS

```
"graphQL": {
      "httpUri": "http://localhost:3000/graphql",
      "wsUri": "ws://localhost:4001/graphql"
    },

to

"graphQL": {
      "httpUri": "https://myproject.herokuapp.com:3000/graphql",
      "wsUri": "wss://myproject.herokuapp.com:4001/graphql"
    },

Note without https and wss, the app is not showing
```

**3) Now on Chrome Console, I have :** 

this warning : 

> 50d72c91808ef7fba57f920b67d152d2d57698eb.js?meteor_js_resource=true:9 WebSocket connection to 'wss://myproject.herokuapp.com:4001/graphql' failed: WebSocket is closed before the connection is established.

and after several warning above, I have this error : 

> 50d72c91808ef7fba57f920b67d152d2d57698eb.js?meteor_js_resource=true:9 WebSocket connection to 'wss://myproject.herokuapp.com:4001/graphql' failed: WebSocket opening handshake timed out

**By using the origin source code from Pup, I can signup on server but I cannot create a new document.**

**Any help, please ?**

Thank you

---

**EDIT 15 JAN 2019**

**4) I remove Port like this : **

    "httpUri": "https://myproject.herokuapp.com/graphql",
    "wsUri": "wss://myproject.herokuapp.com/graphql"

Now, I can create New document on https://myproject.herokuapp.com/documents

but I still have this warning : 

> fe6fa1ac83e19aa2513ac3f97293600e8dc99e8e.js?meteor_js_resource=true:9
> WebSocket connection to 'wss://myproject.herokuapp.com/graphql'
> failed: WebSocket is closed before the connection is established.

and this error :

> WebSocket connection to 'wss://myproject.herokuapp.com/graphql'
> failed: Error during WebSocket handshake: Unexpected response code:
> 503

**any idea ?**

**Thanks**

**Comment by cleverbeagle** [comment]
Hi @TroubadourFabiolas, a quick fix may be this: https://github.com/meteor/meteor/issues/3509#issuecomment-306574572.

Off hand, though, I've seen this warning too and think I can tweak how the PupQL package attaches to Meteor's websocket server. Need to investigate a bit more.

**Comment by cleverbeagle** [comment]
Closing this in favor of #280 (same problem).

**Comment by ayhid** [comment]
> Closing this in favor of #280 (same problem).

Hello,  I am facing the same issue after deploying my app on AWS using mup. I am maybe not seeing the big picture here but I don't understand how the issue described here is related to #280 .

@cleverbeagle could you please explain?

Thanks a lot

**Comment by allenfuller** [comment]
I'm in the same boat. It may be an issue that I just don't understand how to configure the WebSocket uri in production? If anyone can offer some pointers, I'll gladly put together some documentation in a pull request.

**Comment by ayhid** [comment]
@allenfuller I ended up integrating pupql into the boilerplate instead of a node module and omiting subscriptions from all my code.
Not the simplest solution to come up with but its worked for me.

**Comment by cleverbeagle** [comment]
@allenfuller @ayhid's suggestion is best at the moment. The goal is to do what he's described and migrate the code for PupQL into Pup directly (see #284).

**Comment by allenfuller** [comment]
Thanks @cleverbeagle! I'll give that a shot.

@ayhid, have you already started on a PR for #284? If not, I'd be happy to work on it. Also, I noticed a few other places where static cleverbeagle resources are embedded in the boilerplate and you have to do some digging to customize (AWS links especially). I'd be happy to work on a PR to move those into a `Meteor.settings` file so they're easier to customize.

**Comment by ayhid** [comment]
@allenfuller actually I've done all the changes for a project deployed with mup on AWS. But I did not started working on PR for the time being.

If you would like to start working on this I'd be happy to help.
