### ISSUE TITLE
Add ability to attach Meteor's websocket server to GraphQL server in PupQL

### ISSUE THREAD

**Issue by izaa** [cleverbeagle/pup#282]
Hi,

Pup 1 we could easily deploy the app to Galaxy. How to deploy 2.0 to Galaxy and what should be the address of graphql wsUri in settings.json?

**Comment by ayhid** [comment]
It could be a solution to look at this package Swydo/ddp-apollo(https://github.com/Swydo/ddp-apollo#server-setup)
If I trust the description it seems that you can use DDP for GraphQL subscriptions.

I can do a PR for this.
