### ISSUE TITLE
Review deps

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#283]
Looks like a few dependencies are left over from 1.x that need to be pulled out.

**Comment by allenfuller** [comment]
I was _just_ about to open a ticket asking about this...  :)

Here's a few that seem to only be referenced within`package.json` butt not imported anywhere in Pup:

1. apollo-boost
2. apollo-link-ws (commented out in `startup/client/apollo.js`)
3. apollo-link-persisted-queries (commented out in `startup/client/apollo.js`)
4. graphql-subscriptions
5. node-fetch (lots of packages depend on it, so does it need to be defined explicitly?)
6. react-redux
7. redux
8. redux-thunk
9. simpl-schema (commented out in `api/UserSettings/UserSettings.js`)
10. subscriptions-transport-ws

I can start testing removing them, but wanted to submit that list in case it's helpful on this issue.

**Comment by cleverbeagle** [comment]
@allenfuller any help I can get would be greatly appreciated. Do you want to do a PR on this?
