### ISSUE TITLE
Merge PupQL into Pup

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#284]
Reviewing it now (and based on recent questions/issues), I think it'd be wise to just make this a customizable file like anything else in Pup. No need for it to be a package at the moment. Original intent was so you could use it as a standalone server but that's not an immediate need.

**Comment by ayhid** [comment]
I can help with a PR for this, could it be a module under the `api` dir ?

**Comment by cleverbeagle** [comment]
Hey @ayhid, sure thing. I'd like to keep this in the `/startup/server/graphql.js` file where the call to `PupQL` is now. Here's an example of what needs to be done:

```
import { ApolloServer } from 'apollo-server-express';
import { WebApp } from 'meteor/webapp';
import { getUser } from 'meteor/apollo';
import schema from './api';

const server = new ApolloServer({
  ...schema,
  context: async ({ req }) => {
    return {
      user: await getUser(req.headers.authorization),
    };
  },
  uploads: false,
});

server.applyMiddleware({
  app: WebApp.connectHandlers,
  path: '/graphql',
});
```

This omits websockets/subscriptions which I intend to whip up a separate solution for.

**Comment by ayhid** [comment]
By omiting websockets/subscriptions we should refactor the app parts that are using them, is it okay for you ?

**Comment by cleverbeagle** [comment]
Hi @ayhid, yes, for the time being. I'd like to bring them back once I can spend some more time figuring out a better solution.

**Comment by ayhid** [comment]
Hi @cleverbeagle I made a PR here #298  could you please review it when you have some time and tell me if you need me to change something?
