### ISSUE TITLE
Fix @cleverbeagle deps breaking startup

### ISSUE THREAD

**Issue by Raidus** [cleverbeagle/pup#29]
Hi there!

I'm trying to install pup but I'm getting the following error:

```
npm ERR! path /Users/willy/Coding/learning/tutorials/pup/node_modules/.staging/@cleverbeagle/seeder-3f2800ee/node_modules/abab
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/willy/Coding/learning/tutorials/pup/node_modules/.staging/@cleverbeagle/seeder-3f2800ee/node_modules/abab' -> '/Users/willy/Coding/learning/tutorials/pup/node_modules/.staging/abab-d5a1be50'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/willy/.npm/_logs/2017-08-03T10_12_21_407Z-debug.log
```
Are there any issues for NPM 5.3.0 and Node v8.2.1 which I'm using? My operating system  ist OSX Sierra 10.12.6

**NOTE:** 
Afterremoving **cleverbeagle/seeder** & **cleverbeagle/dates** from the package.json, the installation completed.

There might be an issue with these packages and my configuration.

When I'm trying to install these packages manually, I'm getting these log files for cleverbeagle/dates and cleverbeagle/seeder

[2017-08-03T10_21_01_633Z-debug.txt](https://github.com/cleverbeagle/pup/files/1196834/2017-08-03T10_21_01_633Z-debug.txt)
[2017-08-03T10_23_32_196Z-debug.txt](https://github.com/cleverbeagle/pup/files/1196835/2017-08-03T10_23_32_196Z-debug.txt)

**Comment by Raidus** [comment]
This issue can be solved.

It's an issue related to NPM 5.3.0.

Downgrading to NPM 5.2.0 via `npm install -g npm@5.2.0` fixes the issue.

**Comment by TAnas0** [comment]
Hello there,
I am running into the same issue and would appreciate your help.
I am trying to set "pup". I installed all the dependencies and I have run into the same problem you explain in the original post.
I was on the version 5.3.0 of npm, and I downgraded successfullt into the 5.2.0 using the command suggested.
I have also removed both packages @cleverbeagle/dates and @cleverbeagle/seeder from the package.json in the root of the project.

I am unsure about what to do next: running "meteor npm install --save @cleverbeagle" (as it is suggested after "npm start" crashes) leads to errors.

I am a bit confused about what to do next and would highly appreciate your help.
Peace

**Comment by TAnas0** [comment]
Hello,
I have solved my issue and successfully accessed the "pup" platform.
What I did was installing both packages cleverbeagle/dates and cleverbeagle/seeder separately using the following commands:

- `meteor npm install --save @cleverbeagle/dates`

- `meteor npm install --save @cleverbeagle/seeder`

I am wondering: should I re-add the dependency in the package.json for these 2 packages?
Anyways thank you for your help.
Peace

**Comment by cleverbeagle** [comment]
Thanks for reporting this @Raidus and @TAnas0. I noticed this coming up yesterday, too, when I cloned a copy for another project. Something seems to be out of whack with how those two packages are loaded in the app (no major changes to them recently, so @Raidus your NPM hint is helpful; thank you).

**Comment by Raidus** [comment]
@cleverbeagle just one hint:
I've installed your repo for another project and tried to npm install with npm 5.2.0. Surprisingly I didn't work. After checking the first workflow, I've realized that it only works if I **remove the packages cleverbeagle/seeder and cleverbeagle/dates** manually from the **package.json**. Then `npm install` it. After successfully installing the packages I have to manually install both packages via `npm i -S cleverbeagle/seeder cleverbeagle/dates`. This workflow works somehow. Therefore I assume that package.json causes the error.

After removing the old node_modules folder an changing the order in the package.json file npm install works without errors (NPM 5.20/Node 8.2.1)

```
"dependencies": {
    "babel-runtime": "^6.20.0",
    "bcrypt": "^1.0.2",
    "commonmark": "^0.27.0",
    "jquery": "^2.2.4",
    "jquery-validation": "^1.16.0",
    "lodash": "^4.17.4",
    "meteor-node-stubs": "~0.2.4",
    "prop-types": "^15.5.10",
    "react": "^15.5.4",
    "react-addons-pure-render-mixin": "^15.5.2",
    "react-bootstrap": "^0.31.0",
    "react-dom": "^15.5.4",
    "react-router-bootstrap": "^0.24.2",
    "react-router-dom": "^4.1.1",
    "simpl-schema": "^0.3.0",
    "@cleverbeagle/dates": "^0.5.1",
    "@cleverbeagle/seeder": "^1.1.3"
  }
```

**Comment by cleverbeagle** [comment]
@Raidus this seems to be the fix. Combined with the version, it looks like there was a blip between the version of those packages in `package.json` vs. the new `package-lock.json` file (introduced in a recent version of NPM—explaining why the downgrade helped earlier). Your suggestion worked and a test clone with a reinstall of the packages seems to do the trick :)
