### ISSUE TITLE
Layout Problem when opening website in new tab

### ISSUE THREAD

**Issue by kjp17** [cleverbeagle/pup#294]
Something odds happens when open a new tab and load http://localhost:3000/.  It says "Warning: Did not expect server HTML to contain a` <nav> in <div>`".  it will cause the page layout to load incorrectly. So I loaded up vanilla pup and see if there's the same problem. 
 
![screen_shot_2019-04-16_at_6 59 20_pm](https://user-images.githubusercontent.com/5260920/57214372-622ca900-701c-11e9-8b96-764896aee132.png)

This problem goes away after reloading the page.  It only occurs in Chrome but not FIrefox. I am using Mac Chrome 73.0.3683.103.

**Comment by cleverbeagle** [comment]
Hi @kjp17, can confirm this behavior. This has to do with the server side rendering producing a different result than the client.

**Comment by cleverbeagle** [comment]
This appears to be resolved. Closing for now.
