### ISSUE TITLE
upload image feature 

### ISSUE THREAD

**Issue by NuruddinBadawi** [cleverbeagle/pup#295]
hello cleverbeagle, I didn't finde other place to ask you
in my case I want to upload image during add mutation, so what do you suggest fo this ?

and maybe it's good to have it in pup as feature, what do you think ?

**Comment by cleverbeagle** [comment]
Hi @NuruddinBadawi, image uploading won't be added to Pup, however, I'd recommend the [edgee:slingshot](https://atmospherejs.com/edgee/slingshot) package to simplify this and this tutorial:  https://themeteorchef.com/tutorials/uploading-files-to-amazon-s3-with-react
