### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#3]
Add unit tests for Pup features (where it makes sense) and ensure we have clear documentation for how these work and how developers can expand upon them.

**Comment by mhurwi** [comment]
Hi, I love this project, thank you for it.

I'd love to get started with some React component tests, but Jest does not seem to be transpiling the jsx properly.

My test: 

```
import React from 'react';
import { mount } from 'enzyme';

import Foo from './Foo';

it('runs', () => {
  const el = <Foo />;
  expect(mount(el).find('.foo')).toEqual(true);
});
```

And the jest output:

```
 FAIL  imports/ui/components/Foo/Foo.test.js
  ● Test suite failed to run

    /Users/mhurwi/Documents/code/foo/app/imports/ui/components/Foo/Foo.test.js: Unexpected token (7:15)
        5 |
        6 | it('runs', () => {
      > 7 |   expect(mount(<Foo />).find('.foo')).toEqual(true);
          |                ^
        8 | });
        9 |

Test Suites: 1 failed, 1 total
```

Maybe I'm missing some babel config somewhere?

**Comment by cleverbeagle** [comment]
@mhurwi good to hear you got it working. I haven't gone too far beyond just some initial play to get things working with Jest but the above edit looks in line with my own work. If you come across any other gotchas and are willing to share, please do :)

**Comment by acomito** [comment]
I wrote some directions down for setting up enzyme/jest with meteor. It uses MDGs meteor-apollo-startkit repo as an example, but it should translate 100% over to pup.

https://medium.com/@arcomito/setting-up-jest-enzyme-in-a-meteor-js-and-apollo-project-9ceadbcf2fa3

**Comment by cleverbeagle** [comment]
Thanks @acomito. This is currently backlogged for me but when I sit down to do it I'll take this into account.

P.S. Are you open to doing a PR on this? Willing to pay to get it done properly.

**Comment by acomito** [comment]
I think it's not too much more work than adding a babelrc file and the mocks folder. I'll take a look.

**Comment by cleverbeagle** [comment]
Cool, appreciate it @acomito :)
