### ISSUE TITLE
PWA Support

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#30]
Need to be able to meet these requirements: https://developers.google.com/web/progressive-web-apps/checklist.

Of note, the service worker is a no-go in Meteor unless we implement a monkey patch like [this](https://github.com/NitroBAY/meteor-service-worker).

**Comment by merlinpatt** [comment]
# Baseline

- [ ] [Site is served over HTTPS](https://developers.google.com/web/progressive-web-apps/checklist#site-is-served-over-https)
- [ ] [Pages are responsive on tablets & mobile devices](https://developers.google.com/web/progressive-web-apps/checklist#pages-are-responsive-on-tablets--mobile-devices)
- [ ] [All app URLs load while offline](https://developers.google.com/web/progressive-web-apps/checklist#all-app-urls-load-while-offline)
- [ ] [Metadata provided for Add to Home screen](https://developers.google.com/web/progressive-web-apps/checklist#metadata-provided-for-add-to-home-screen)
- [ ] [First load fast even on 3G](https://developers.google.com/web/progressive-web-apps/checklist#first-load-fast-even-on-3g)
- [ ] [Site works cross-browser](https://developers.google.com/web/progressive-web-apps/checklist#site-works-cross-browser)
- [ ] [Page transitions don't feel like they block on the network](https://developers.google.com/web/progressive-web-apps/checklist#page-transitions-dont-feel-like-they-block-on-the-network)
- [ ] [Each page has a URL](https://developers.google.com/web/progressive-web-apps/checklist#each-page-has-a-url)

# Exemplary

## Indexability & social

- [ ] [Site's content is indexed by Google](https://developers.google.com/web/progressive-web-apps/checklist#sites-content-is-indexed-by-google)
- [ ] [Schema.org metadata is provided where appropriate](https://developers.google.com/web/progressive-web-apps/checklist#schemaorg-metadata-is-provided-where-appropriate)
- [ ] [Social metadata is provided where appropriate](https://developers.google.com/web/progressive-web-apps/checklist#social-metadata-is-provided-where-appropriate)
- [ ] [Canonical URLs are provided when necessary](https://developers.google.com/web/progressive-web-apps/checklist#canonical-urls-are-provided-when-necessary)
- [ ] [Pages use the History API](https://developers.google.com/web/progressive-web-apps/checklist#pages-use-the-history-api)

## User experience

- [ ] [Content doesn't jump as the page loads](https://developers.google.com/web/progressive-web-apps/checklist#content-doesnt-jump-as-the-page-loads)
- [ ] [Pressing back from a detail page retains scroll position on the previous list page](https://developers.google.com/web/progressive-web-apps/checklist#pressing-back-from-a-detail-page-retains-scroll-position-on-the----------previous-list-page)
- [ ] [When tapped, inputs aren't obscured by the on screen keyboard](https://developers.google.com/web/progressive-web-apps/checklist#when-tapped-inputs-arent-obscured-by-the-on-screen-keyboard)
- [ ] [Content is easily shareable from standalone or full screen mode](https://developers.google.com/web/progressive-web-apps/checklist#content-is-easily-shareable-from-standalone-or-full-screen-mode)
- [ ] [Site is responsive across phone, tablet and desktop screen sizes](https://developers.google.com/web/progressive-web-apps/checklist#site-is-responsive-across-phone-tablet-and-desktop-screen-sizes)
- [ ] [Any app install prompts are not used excessively](https://developers.google.com/web/progressive-web-apps/checklist#any-app-install-prompts-are-not-used-excessively)
- [ ] [The Add to Home Screen prompt is intercepted](https://developers.google.com/web/progressive-web-apps/checklist#the-add-to-home-screen-prompt-is-intercepted)

## Performance

- [ ] [First load very fast even on 3G](https://developers.google.com/web/progressive-web-apps/checklist#first-load-very-fast-even-on-3g)

## Caching

- [ ] [Site uses cache-first networking](https://developers.google.com/web/progressive-web-apps/checklist#site-uses-cache-first-networking)
- [ ] [Site appropriately informs the user when they're offline](https://developers.google.com/web/progressive-web-apps/checklist#site-appropriately-informs-the-user-when-theyre-offline)

## Push notifications

- [ ] [Provide context to the user about how notifications will be used](https://developers.google.com/web/progressive-web-apps/checklist#provide-context-to-the-user-about-how-notifications-will-be-used)
- [ ] [UI encouraging users to turn on Push Notifications must not be overly aggressive.](https://developers.google.com/web/progressive-web-apps/checklist#ui-encouraging-users-to-turn-on-push-notifications-must-not-be----------overly-aggressive)
- [ ] [Site dims the screen when permission request is showing](https://developers.google.com/web/progressive-web-apps/checklist#site-dims-the-screen-when-permission-request-is-showing)
- [ ] [Push notifications must be timely, precise and relevant](https://developers.google.com/web/progressive-web-apps/checklist#push-notifications-must-be-timely-precise-and-relevant)
- [ ] [Provides controls to enable and disable notifications](https://developers.google.com/web/progressive-web-apps/checklist#provides-controls-to-enable-and-disable-notifications)

## Additional features

- [ ] [User is logged in across devices via Credential Management API](https://developers.google.com/web/progressive-web-apps/checklist#user-is-logged-in-across-devices-via-credential-management-api)
- [ ] [User can pay easily via native UI from Payment Request API.](https://developers.google.com/web/progressive-web-apps/checklist#user-can-pay-easily-via-native-ui-from-payment-request-api)

**Comment by merlinpatt** [comment]
# Exemplary

## Indexability & social

- [ ] [Site's content is indexed by Google](https://developers.google.com/web/progressive-web-apps/checklist#sites-content-is-indexed-by-google)
- [ ] [Schema.org metadata is provided where appropriate](https://developers.google.com/web/progressive-web-apps/checklist#schemaorg-metadata-is-provided-where-appropriate)
- [ ] [Social metadata is provided where appropriate](https://developers.google.com/web/progressive-web-apps/checklist#social-metadata-is-provided-where-appropriate)
- [ ] [Canonical URLs are provided when necessary](https://developers.google.com/web/progressive-web-apps/checklist#canonical-urls-are-provided-when-necessary)
- [ ] [Pages use the History API](https://developers.google.com/web/progressive-web-apps/checklist#pages-use-the-history-api)

## User experience

- [ ] [Content doesn't jump as the page loads](https://developers.google.com/web/progressive-web-apps/checklist#content-doesnt-jump-as-the-page-loads)
- [ ] [Pressing back from a detail page retains scroll position on the previous list page](https://developers.google.com/web/progressive-web-apps/checklist#pressing-back-from-a-detail-page-retains-scroll-position-on-the----------previous-list-page)
- [ ] [When tapped, inputs aren't obscured by the on screen keyboard](https://developers.google.com/web/progressive-web-apps/checklist#when-tapped-inputs-arent-obscured-by-the-on-screen-keyboard)
- [ ] [Content is easily shareable from standalone or full screen mode](https://developers.google.com/web/progressive-web-apps/checklist#content-is-easily-shareable-from-standalone-or-full-screen-mode)
- [ ] [Site is responsive across phone, tablet and desktop screen sizes](https://developers.google.com/web/progressive-web-apps/checklist#site-is-responsive-across-phone-tablet-and-desktop-screen-sizes)
- [ ] [Any app install prompts are not used excessively](https://developers.google.com/web/progressive-web-apps/checklist#any-app-install-prompts-are-not-used-excessively)
- [ ] [The Add to Home Screen prompt is intercepted](https://developers.google.com/web/progressive-web-apps/checklist#the-add-to-home-screen-prompt-is-intercepted)

## Performance

- [ ] [First load very fast even on 3G](https://developers.google.com/web/progressive-web-apps/checklist#first-load-very-fast-even-on-3g)

## Caching

- [ ] [Site uses cache-first networking](https://developers.google.com/web/progressive-web-apps/checklist#site-uses-cache-first-networking)
- [ ] [Site appropriately informs the user when they're offline](https://developers.google.com/web/progressive-web-apps/checklist#site-appropriately-informs-the-user-when-theyre-offline)

## Push notifications

- [ ] [Provide context to the user about how notifications will be used](https://developers.google.com/web/progressive-web-apps/checklist#provide-context-to-the-user-about-how-notifications-will-be-used)
- [ ] [UI encouraging users to turn on Push Notifications must not be overly aggressive.](https://developers.google.com/web/progressive-web-apps/checklist#ui-encouraging-users-to-turn-on-push-notifications-must-not-be----------overly-aggressive)
- [ ] [Site dims the screen when permission request is showing](https://developers.google.com/web/progressive-web-apps/checklist#site-dims-the-screen-when-permission-request-is-showing)
- [ ] [Push notifications must be timely, precise and relevant](https://developers.google.com/web/progressive-web-apps/checklist#push-notifications-must-be-timely-precise-and-relevant)
- [ ] [Provides controls to enable and disable notifications](https://developers.google.com/web/progressive-web-apps/checklist#provides-controls-to-enable-and-disable-notifications)

## Additional features

- [ ] [User is logged in across devices via Credential Management API](https://developers.google.com/web/progressive-web-apps/checklist#user-is-logged-in-across-devices-via-credential-management-api)
- [ ] [User can pay easily via native UI from Payment Request API.](https://developers.google.com/web/progressive-web-apps/checklist#user-can-pay-easily-via-native-ui-from-payment-request-api)

**Comment by msavin** [comment]
iOS 12 is coming with some big PWA updates!

https://twitter.com/mhartington/status/1089292031548145666
