### ISSUE TITLE
Is NewDocument Component used somewhere ?

### ISSUE THREAD

**Issue by ayhid** [cleverbeagle/pup#300]
I can not find where this component `ui/pages/NewDocument/index.js` is used.
I have a hard time figuring out how the New Document feature works.
@cleverbeagle could you please give me some hints about it ?

Thanks a lot

**Comment by cleverbeagle** [comment]
This needs to be deleted. It used to be in use before 2.0.

**Comment by ayhid** [comment]
PR #301
