### ISSUE TITLE
Not succeeding to start the project

### ISSUE THREAD

**Issue by nouboussijunior** [cleverbeagle/pup#303]
Hello.
I cloned the repo and tried to deploy it.
This is the error I am getting since:

`W20190618-19:19:49.780(1)? (STDERR) [Pup] Woof! OAuth settings are not configured. OAuth login will not function. See https://cleverbeagle.com/pup/v2/accounts/oauth#setting-oauth-credentials for configuration instructions.
W20190618-19:19:49.859(1)? (STDERR) C:\Users\Dell\AppData\Local\.meteor\packages\promise\0.11.1\npm\node_modules\meteor-promise\promise_server.js:218
W20190618-19:19:49.861(1)? (STDERR)       throw error;
W20190618-19:19:49.861(1)? (STDERR)       ^
W20190618-19:19:49.861(1)? (STDERR)
W20190618-19:19:49.862(1)? (STDERR) TypeError: Cannot read property 'supportEmail' of undefined
W20190618-19:19:49.862(1)? (STDERR)     at emailTemplates.js (startup/server/accounts/emailTemplates.js:13:47)
W20190618-19:19:49.863(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190618-19:19:49.863(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190618-19:19:49.863(1)? (STDERR)     at Module.moduleLink [as link] (C:\Users\Dell\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20190618-19:19:49.864(1)? (STDERR)     at index.js (startup/server/accounts/index.js:1:61)
W20190618-19:19:49.864(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190618-19:19:49.865(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190618-19:19:49.866(1)? (STDERR)     at Module.moduleLink [as link] (C:\Users\Dell\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20190618-19:19:49.871(1)? (STDERR)     at index.js (startup/server/index.js:1:8)
W20190618-19:19:49.874(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190618-19:19:49.875(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190618-19:19:49.876(1)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20190618-19:19:49.877(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\app\app.js:12422:15
W20190618-19:19:49.878(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\boot.js:411:36
W20190618-19:19:49.880(1)? (STDERR)     at Array.forEach (<anonymous>)
W20190618-19:19:49.882(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\boot.js:220:19
W20190618-19:19:49.886(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\boot.js:471:5
W20190618-19:19:49.886(1)? (STDERR)     at Function.run (G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\profile.js:510:12)
W20190618-19:19:49.897(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\boot.js:470:11
=> Exited with code: 1
W20190618-19:20:03.262(1)? (STDERR) [Pup] Woof! OAuth settings are not configured. OAuth login will not function. See https://cleverbeagle.com/pup/v2/accounts/oauth#setting-oauth-credentials for configuration instructions.
W20190618-19:20:04.034(1)? (STDERR) C:\Users\Dell\AppData\Local\.meteor\packages\promise\0.11.1\npm\node_modules\meteor-promise\promise_server.js:218
W20190618-19:20:04.035(1)? (STDERR)       throw error;
W20190618-19:20:04.036(1)? (STDERR)       ^
W20190618-19:20:04.039(1)? (STDERR)
W20190618-19:20:04.040(1)? (STDERR) TypeError: Cannot read property 'supportEmail' of undefined
W20190618-19:20:04.042(1)? (STDERR)     at emailTemplates.js (startup/server/accounts/emailTemplates.js:13:47)
W20190618-19:20:04.043(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190618-19:20:04.049(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190618-19:20:04.051(1)? (STDERR)     at Module.moduleLink [as link] (C:\Users\Dell\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20190618-19:20:04.053(1)? (STDERR)     at index.js (startup/server/accounts/index.js:1:61)
W20190618-19:20:04.055(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190618-19:20:04.058(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190618-19:20:04.061(1)? (STDERR)     at Module.moduleLink [as link] (C:\Users\Dell\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20190618-19:20:04.063(1)? (STDERR)     at index.js (startup/server/index.js:1:8)
W20190618-19:20:04.064(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190618-19:20:04.066(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190618-19:20:04.072(1)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20190618-19:20:04.074(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\app\app.js:12422:15
W20190618-19:20:04.075(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\boot.js:411:36
W20190618-19:20:04.077(1)? (STDERR)     at Array.forEach (<anonymous>)
W20190618-19:20:04.079(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\boot.js:220:19
W20190618-19:20:04.083(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\boot.js:471:5
W20190618-19:20:04.084(1)? (STDERR)     at Function.run (G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\profile.js:510:12)
W20190618-19:20:04.085(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\boot.js:470:11
=> Exited with code: 1
W20190618-19:20:16.574(1)? (STDERR) [Pup] Woof! OAuth settings are not configured. OAuth login will not function. See https://cleverbeagle.com/pup/v2/accounts/oauth#setting-oauth-credentials for configuration instructions.
W20190618-19:20:16.671(1)? (STDERR) C:\Users\Dell\AppData\Local\.meteor\packages\promise\0.11.1\npm\node_modules\meteor-promise\promise_server.js:218
W20190618-19:20:16.676(1)? (STDERR)       throw error;
W20190618-19:20:16.679(1)? (STDERR)       ^
W20190618-19:20:16.680(1)? (STDERR)
W20190618-19:20:16.683(1)? (STDERR) TypeError: Cannot read property 'supportEmail' of undefined
W20190618-19:20:16.685(1)? (STDERR)     at emailTemplates.js (startup/server/accounts/emailTemplates.js:13:47)
W20190618-19:20:16.690(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190618-19:20:16.691(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190618-19:20:16.694(1)? (STDERR)     at Module.moduleLink [as link] (C:\Users\Dell\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20190618-19:20:16.697(1)? (STDERR)     at index.js (startup/server/accounts/index.js:1:61)
W20190618-19:20:16.698(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190618-19:20:16.700(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190618-19:20:16.702(1)? (STDERR)     at Module.moduleLink [as link] (C:\Users\Dell\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20190618-19:20:16.707(1)? (STDERR)     at index.js (startup/server/index.js:1:8)
W20190618-19:20:16.708(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190618-19:20:16.710(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190618-19:20:16.711(1)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20190618-19:20:16.713(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\app\app.js:12422:15
W20190618-19:20:16.714(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\boot.js:411:36
W20190618-19:20:16.720(1)? (STDERR)     at Array.forEach (<anonymous>)
W20190618-19:20:16.722(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\boot.js:220:19
W20190618-19:20:16.723(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\boot.js:471:5
W20190618-19:20:16.727(1)? (STDERR)     at Function.run (G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\profile.js:510:12)
W20190618-19:20:16.728(1)? (STDERR)     at G:\App_Meditations\React-Meteor\pup\.meteor\local\build\programs\server\boot.js:470:11`

Please anyone could help?

**Comment by ayhid** [comment]
@nouboussijunior could you please provide more information ? what command have you tried to run ?

**Comment by nouboussijunior** [comment]
I just followed the readme.md from the repo
meteor npm install and when I try to run I get that error.

**Comment by cleverbeagle** [comment]
This looks like a missing settings file. Did you start the app with `meteor npm start` or `meteor --settings settings-development.json`?

**Comment by nouboussijunior** [comment]
I started with `npm run dev`
what should I have used ??

**Comment by ayhid** [comment]
try `meteor npm run dev`

**Comment by nouboussijunior** [comment]
> meteor npm run dev

Yeah it worked.
But please what is the difference ?

**Comment by ayhid** [comment]
> > meteor npm run dev
> 
> Yeah it worked.
> But please what is the difference ?

Perfect, it is explained here: [Cloning & Installing Dependencies](https://cleverbeagle.com/pup/v2/cloning-installing-dependencies)

**Comment by nouboussijunior** [comment]
Thank you so much
