### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by wortkotze** [cleverbeagle/pup#308]
Hi, 

I try to setup a fileupload with apollo-upload-client and server. but i dont get it to work any tips?

I changed already 

> // new HttpLink({
  new createUploadLink({

added Upload

the client is sending the information but fails with 500 

![Bildschirmfoto 2019-06-28 um 21 53 09](https://user-images.githubusercontent.com/1026043/60378337-2e07b000-99ef-11e9-8c35-fdb3bef18b77.png)
![Bildschirmfoto 2019-06-28 um 21 52 59](https://user-images.githubusercontent.com/1026043/60378338-2e07b000-99ef-11e9-8da8-182470781a8f.png)

any idea welcomed :) thx

**Comment by wortkotze** [comment]
I removed PupQL out of the sourcecode ... now its working with standard apollo client

**Comment by jeffreykrodgers** [comment]
I'm having the same problem, but I'm unsure of exactly how to remove PupQL without breaking everything. Any guidance would be appreciated

**Comment by cleverbeagle** [comment]
@jeffreykrodgers if you take a look at the latest release, you should be able to copy these files and avoid any issues:

startup/server/graphql.js
startup/client/apollo.js

And in the /api/Documents/mutations.js file, remove any reference to the .publish() method.

Let me know if that helps/works!

**Comment by jeffreykrodgers** [comment]
Many thanks my dude. In addition to your fix I also had to modify the api.js default export to match the latest release (use `makeExectuableSchema(schema)`) and that got it working. 

I'm still having the same original problem as OP, but I don't think its pup's fault. I'll see if I can figure out why and report back.

**Comment by jeffreykrodgers** [comment]
OPs solution, plus removing `uploads: false` from startup/server/graphql.js got me the last mile. Everythings working great :)

Thanks for all you do @cleverbeagle

**Comment by cleverbeagle** [comment]
Good to hear you got this resolved @jeffreykrodgers :) Thanks for using Pup!
