### ISSUE TITLE
User name not showing when logging in with Google

### ISSUE THREAD

**Issue by pilarArr** [cleverbeagle/pup#31]
I believe the code to fix would be [this](https://github.com/cleverbeagle/pup/blob/master/imports/ui/components/OAuthLoginButton/OAuthLoginButton.js#L20), the fix would be to request the `profile` also.

The function that gives and empty value if you log in with Google is [this one](https://github.com/cleverbeagle/pup/blob/master/imports/ui/layouts/App/App.js#L86).

**Comment by cleverbeagle** [comment]
Hi @pilarArr having trouble confirming this one. When logging in with multiple Google accounts and a fresh `Meteor.users` collection, the username is displaying as expected. Can you provide a screencap/video of what you're experiencing?

![pup-google-login](https://user-images.githubusercontent.com/23730234/29072061-d51fd574-7c0b-11e7-96cb-6f98c17db51d.gif)

**Comment by pilarArr** [comment]
Hi @cleverbeagle, 
Sorry for the delay, this would be the screencap of what I'm seeing, I also deleted the users collection before trying like you said and still nothing. I also tried with different google accounts and still got the same.

![movie1](https://user-images.githubusercontent.com/26302137/29079935-cd8d46cc-7c5e-11e7-87c6-4cb561693818.gif)

**Comment by pilarArr** [comment]
Also this is the entry that is created in the Mongo Collection. 
Because my profile is empty every time, the name is always empty and this only happens with Google, with Facebook it works.
![screen region 2017-08-09 at 08 42 08](https://user-images.githubusercontent.com/26302137/29109381-1655bac2-7ce3-11e7-9e95-33ff10211b22.png)

**Comment by zeiitoun** [comment]
Pretty sure It's because OAuth usez Google (plus) to retrieve first and last name, and you don't have any.

**Comment by cleverbeagle** [comment]
Interesting! Kind of wonky on Google's part, but makes sense as to why we'd see the difference. I'm not sure if we should qualify this as a bug since it's technically working as expected. Maybe the fix here is to just display the email address if we detect an empty name string?

P.S. @pilarArr and @zeiitoun  do you have an email I can get in touch at (or could you email [ryan.glover@cleverbeagle.com](mailto:ryan.glover@cleverbeagle.com))? Wanted to see if either of you would be interested in helping with Pup.

**Comment by zeiitoun** [comment]
In the meteor documentation, it's specified that you can add options for google services when you call Meteor.loginWithGoogle. (https://docs.meteor.com/api/accounts.html#Meteor-loginWith\<ExternalService\>)

This options may include Google’s additional URI parameters (https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters) such as the scope that might be intersting in our case.

You could modify the login scope to "https://www.googleapis.com/auth/plus.login"? Which will ask the user to suscribe to Google Plus if he doesn't have any account 
**(bonus point : It's the recommended login scope, meteor should change to this one)**

**Comment by pilarArr** [comment]
I went around this by changing the option `requestPermissions` to `['email', 'profile']`. That fills the profile and fixes the empty name. 

I'm not sure everyone wants to have a Google Plus account to sign up with their Google account, seems like an unnecessary extra step to create a Google Plus account just to sing up with Google, but that's just my newbie opinion 😕 

P.S. @cleverbeagle I've sent you an email 😄
