### ISSUE TITLE
Redirect to specific route based on user role

### ISSUE THREAD

**Issue by ayhid** [cleverbeagle/pup#311]
Hello, is there a way to perform this with the current pup version ?
Is there some documentation about the afterLoginPath props in route components ?

**Comment by cleverbeagle** [comment]
Unofficially, yes. You could do it using a manual `history.push()` from something like the `/` route (or `<Index />` component), or piggyback on the existing `<Authenticated />` and `<Authorized />` components to do what you want.

I'd go for the latter as the bulk of the work is already done for you.
