### ISSUE TITLE
Can we set context.user when server side rendering?

### ISSUE THREAD

**Issue by allenfuller** [cleverbeagle/pup#312]
Reading through the [docs on SSR](https://cleverbeagle.com/pup/v2/extras/server-side-rendering), I came across this line:

> Static pages and pages with dynamic data will automatically be server-side rendered as expected. The only exception to this rule is that pages that are rendered using the [Authenticated or Authorized components](https://cleverbeagle.com/pup/v2/routing/defining-routes) will block the initial SSR request, so only the navigation elements of those pages will be SSR'd (this is just how SSR works, not a limitation of Pup).

Looking at the code for Authenticated and Public routes, I'm not sure I understand why this is. Can you explain it and how we might be able to achieve SSR rendering w/ these kinds of routes?

Thanks!

**Comment by cleverbeagle** [comment]
This is because there is no user present when the initial request comes into the server. For Meteor, the token for this is stored in local storage (not cookies like other forms of auth), so there's no way to know "who" is connecting until the client/browser loads up.

This means that the `<Authenticated />` component doesn't have an authenticated user and redirects like you'd expect a logged out user would be.

**Comment by allenfuller** [comment]
Awesome, thanks Ryan! 

My use case is that I'm trying to use the `SEO` component within routes, but it won't render early enough. I've added a top-level `SEO` reference in `ui/layouts/App/index.js` that renders, but if I put one in a specific Authenticated route, it won't render in the page source, and thus won't work for the Facebook scraper.

One way I'm considering getting around it is to use state to update the "parent" SEO component, then update from child routes by passing down a prop function to update state, but maybe there's another way?

**Comment by cleverbeagle** [comment]
Some thoughts on this...

If the point of the SSR is for the benefit of Google, then this will be impossible. The reason why is that Google would essentially need to have a user account that we could authenticate (for example, they'd pass a login token and we'd say "oh this is Google's user" and set them on the GraphQL context).

We *could* do this by having a user-agent check when rendering but unless there's a way to do this securely (i.e., make it unspoofable) then it may be a no go.
