### ISSUE TITLE
See where we can use react-hooks instead of class components

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#322]
h/t Peter D. for bringing this up...

Need to review components to see where React hooks would be more appropriate than class components.

**Comment by ArchiCroc** [comment]
Hooks are great and now that Apollo has their hooks in beta, I took a stab at converting my pup fork over to use them. Take a look at this branch where I combined my various feature branches I've been tinkering with. https://github.com/ArchiCroc/pup/blob/feature/combined/ui/documents/Documents.js

**Comment by cleverbeagle** [comment]
Hey @ArchiCroc, thanks for sharing. I'll take a look.
