### ISSUE TITLE
How to Connect to a react native app with pupql

### ISSUE THREAD

**Issue by pisacode** [cleverbeagle/pup#327]

**Comment by cleverbeagle** [comment]
Hey @pisacode, you can connect your app using the Apollo React Native integration: https://www.apollographql.com/docs/react/recipes/react-native/. You can just point the connection to your server that's running PupQL/your GraphQL server (e.g., http://localhost:4000/graphql).

**Comment by nbedevi** [comment]
Hey @cleverbeagle, how to make login and signup in Pup using GraphQL? 
I want to use it in my mobile app.

**Comment by cleverbeagle** [comment]
@nbedevi you will need to connect to Meteor using something like [ddp.js](https://www.npmjs.com/package/ddp.js) and then store the user's credentials in your mobile app's local storage.

**Comment by nbedevi** [comment]
Sorry for asking again, what is the query should I send it to the server?
