### ISSUE TITLE
compose is not a function

### ISSUE THREAD

**Issue by tab00** [cleverbeagle/pup#329]
After updating NPM packages to their latest versions I get the above error.

The offending code is in ui/pages/Documents/index.js.

**Comment by cleverbeagle** [comment]
@tab00 what's the error? "compose is not a function?"

**Comment by cleverbeagle** [comment]
@tab00 this sounds like an issue with Apollo. I know they just did a major upgrade which isn't supported by Pup yet. Going to close this for now.

**Comment by tab00** [comment]
`compose` has been moved out of react-apollo, so I think you just need to instead do:

`import compose from 'lodash.flowright';`
