### ISSUE TITLE
Update Apollo Client and Apollo Server Usage

### ISSUE THREAD

**Issue by tab00** [cleverbeagle/pup#330]
`dataSources` allows for better separation of db with the app, so that you could more quickly and easily switch db in future (e.g. to an SQL one).

See below new syntax for initializing ApolloServer with `dataSources` and `subscriptions`:

```js
const server = new ApolloServer({
    context: async ({ req, connection }) => {
      if (connection) { // check connection for metadata. Needed for Subscriptions to work.
        return { ...connection.context }
      }
      return { user: await getUser(req.headers.authorization) }
    },
    typeDefs,
    resolvers,
    dataSources: () => ({
      dsBooks: new DSBooks({ db })
    }),
    subscriptions: {
      path: "/subscriptions",
    }
  })
```

See full code of a simple working example app at https://github.com/tab00/test-meteor-apollo

**Comment by cleverbeagle** [comment]
@tab00 where does data sources appear...in `context` of the resolver or somewhere else?

**Comment by tab00** [comment]
Yes, you get the `dataSources` in context in resolvers as you can see inhttps://github.com/tab00/test-meteor-apollo/blob/eac5c06316a3573e269bf553b526027cb5372b33/server/resolvers.js#L15

**Comment by cleverbeagle** [comment]
Reviewing some of the changes now and it seems like a lot will be worthwhile. Specifically, re-implementing subscriptions and making use of hooks.

**Comment by cleverbeagle** [comment]
https://www.apollographql.com/docs/apollo-server/features/file-uploads/
