### ISSUE TITLE
Application stuck when trying to run. 

### ISSUE THREAD

**Issue by ajitgoel** [cleverbeagle/pup#331]
I have run the `meteor npm run dev `command to run the application but it is stuck at `Loading apollo@3.0.1...` step for a long long time(more than 20 minutes). I have stopped and started a couple of times and I still have the same issue.  Can someone please help?

Similarly for [pup v1x](https://cleverbeagle.com/pup/v1/getting-started#setting-your-own-origin-remote), running the command `meteor npm start` throws the `npm ERR! missing script: start `error. 

**Logs**
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\AjitGoel\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.1\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe',
1 verbose cli   'C:\\Users\\AjitGoel\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.1\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v8.15.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Users\AjitGoel\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\Users\AjitGoel\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\Users\AjitGoel\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Users\AjitGoel\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (C:\Users\AjitGoel\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (C:\Users\AjitGoel\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (C:\Users\AjitGoel\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Users\AjitGoel\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\read-package-json\read-json.js:364:12
4 verbose stack     at C:\Users\AjitGoel\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:90:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd c:\temp\commonmembership2
6 verbose Windows_NT 10.0.17763
7 verbose argv "C:\\Users\\AjitGoel\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.1\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe" "C:\\Users\\AjitGoel\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.1\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 verbose node v8.15.1
9 verbose npm  v6.9.0
10 error missing script: start
11 verbose exit [ 1, true ]

**Comment by cleverbeagle** [comment]
Hi @ajitgoel, okay good! That error means that there was a JavaScript promise being called that failed, but didn't have the proper code for handling its error implemented. Based on the path, it doesn't look like it's coming from a file in Pup but rather a dependency. If you start making changes to the app and it restarts, does that error still show?

**Comment by ajitgoel** [comment]
Hello Ryan,
The errors do not show again, after I restart the application.
