### ISSUE TITLE
Access Meteor settings file from Jest?

### ISSUE THREAD

**Issue by allenfuller** [cleverbeagle/pup#337]
Trying to run tests that include a test call to a third-party API, the key for which is obviously stored in a settings file.

However, Jest does not have access to Meteor's settings file. So.....

Any advice on how to run Pup tests with Jest that need to reference the Meteor settings file?

Thanks!

**Comment by cleverbeagle** [comment]
Hey @allenfuller you just need to update the Meteor mock here: https://github.com/cleverbeagle/pup/blob/master/tests/__mocks__/meteor/meteor.js#L21

**Comment by ayhid** [comment]
Having tests rely on third-party api is not usually a good thing.
you should consider mocking the api.
