### ISSUE TITLE
graphQL httpUri on staging and production settings

### ISSUE THREAD

**Issue by bardiaheshmati** [cleverbeagle/pup#338]
i see that Apollo client is refering to GraphQL httpUri in the settings file in the development settings. how should i alter this for staging and production, would localhost work on both ?

`"httpUri": "http://localhost:3000/graphql"` or should i change it to the url that each enviroment is sitting att like "https://domain.com/graphql" ?

**Comment by cleverbeagle** [comment]
Hi, @bardiaheshmati that's correct. Take a look at the docs on creating multiple settings files here: https://cleverbeagle.com/pup/v2/settings-configuration/settings-json. Just swap out URLs as necessary.
