### ISSUE TITLE
Why is document methods located oustide of the server folder ?

### ISSUE THREAD

**Issue by zeiitoun** [cleverbeagle/pup#34]
Since the methods of the documents are imported on the startup of the server : 

`import '../../api/Documents/methods';`

Seems clearer to me if the methods are located in the server folder since we don't import this file on client anymore. (Like we used to do with base)

**Comment by cleverbeagle** [comment]
This is part of the [Meteor Guide structure](https://guide.meteor.com/structure.html). I'm not wholly in agreement with it either, but I'd like to follow that as closely as possible for now to avoid too much variance between Pup/other Meteor code folks might find in the wild (especially TMC tutorials).

**Comment by zeiitoun** [comment]
Isn't it because meteor tutorial and guide use ValidatedMethod on the methods ? (Which make the call of methods.js from the client mandatory) Like on their todo app ? 

I'm a bit skeptical about this, especially if methods.js for Users is located in the server folder.

**Comment by cleverbeagle** [comment]
That would be a question for the Meteor folks. 

As I understand it, it's to keep all of your data-related code under the `/imports/api` directory as splitting it off to the server doesn't serve much utility. In respect to that nested `/server` directory, this takes advantage of Meteor's ability to ensure that code can only be imported into a server context (as opposed to using `Meteor.isServer` everywhere).

From the sound of the roadmap, [there's a goal to move away from the `/imports` directory entirely](https://github.com/meteor/meteor/blob/devel/Roadmap.md#get-rid-of-the-imports-directory), so I suppose it's a matter of time and keeping an eye on it.
