### ISSUE TITLE
Wildcard instead of GraphQL?

### ISSUE THREAD

**Issue by brillout** [cleverbeagle/pup#344]
Hi!

I'm curious, what do you think of using [Wildcard API](https://github.com/reframejs/wildcard-api#readme) instead of GraphQL?

As far as I can tell, Wildcard would be a better fit. What do you think?

**Comment by cleverbeagle** [comment]
Hey @brillout thanks for sharing this! At this point Pup is locked in on GraphQL but I'm working on something new where Wildcard may come in handy.

**Comment by brillout** [comment]
:+1: Can I know about this new project? :-)

**Comment by cleverbeagle** [comment]
@brillout yeah! Can you shoot me an email (ryan.glover@cleverbeagle.com) so we can chat privately?
