### ISSUE TITLE
Upgrade to latest version of alanning:roles

### ISSUE THREAD

**Issue by robguinness** [cleverbeagle/pup#345]
I just learned that Pup is using a pretty ancient version of `alanning:roles` (v1.2.19 whereas latest version is v3.2.2). Are there any plans to upgrade this package in the project? I think it is not so straight-forward. At least, I have not managed in one Pup-based project.

**Comment by evolross** [comment]
Just an FYI the v3 of `alanning:roles` requires running not one, but two upgrade scripts on your databse. Both of which have [reported issues](https://forums.meteor.com/t/alanning-roles-v3-released/50799/18?u=evolross). And v3 now adds an entirely new database collection and publication and requires more trips to the database to do the same thing. There's some controversy on upgrading.  So FYI.
