### ISSUE TITLE
Error when I build for production: TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by pc-magas** [cleverbeagle/pup#35]
I try to build the boilerplate for probuction on a Ubuntu GNU/Linux 16.04 machine. To do that I used these commands:

```bash
git clone https://github.com/cleverbeagle/pup.git pup2
cd pup2
npm install
meteor build ~/builds
cp settings-development.json  ~/builds/settings.json
```

Afterwards I went to folder `~/builds` and I did typed these commands:

```bash
cd ~/builds
tar -xvf pup2.tar.gz
cd bundle
cd programs/server
npm install
cd ../../
export MONGO_URL="mongodb://localhost:27017/tesedb"; 
export  ROOT_URL="192.168.30.137:3821"; 
export PORT=3821; 
export METEOR_SETTINGS="$(cat ../settings.json)"
node main.js
```

The last command (`node main.js`) returns the following error:

> 
> /home/pcmagas/builds/bundle/programs/server/boot.js:391
> }).run();
>    ^
> 
> TypeError: Cannot read property 'slice' of null
>     at packages/meteor.js:1221:19
>     at packages/meteor.js:1233:4
>     at packages/meteor.js:1380:3
>     at /home/pcmagas/builds/bundle/programs/server/boot.js:338:34
>     at Array.forEach (native)
>     at Function._.each._.forEach (/home/pcmagas/builds/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
>     at /home/pcmagas/builds/bundle/programs/server/boot.js:158:5
>     at /home/pcmagas/builds/bundle/programs/server/boot.js:387:5
>     at Function.run (/home/pcmagas/builds/bundle/programs/server/profile.js:510:12)
>     at /home/pcmagas/builds/bundle/programs/server/boot.js:386:11

**Comment by cleverbeagle** [comment]
@pc-magas will have to take a look at this. Haven't tried to do any manual builds yet, though, I know this has been deployed into production so likely something small.

**Comment by pc-magas** [comment]
For what I have found is that if the `ROOT_URL` enviromental variable does not start either with *http://* or *https://* it throws this error.

**Comment by cleverbeagle** [comment]
Ah, that makes sense. This may be something internal in Meteor getting caught up (we don't fudge with environment variables at all in Pup). The big hint is that the error is coming from Underscore which is used pretty heavily in Meteor internals.
