### ISSUE TITLE
Password only oauth possible?

### ISSUE THREAD

**Issue by odesey** [cleverbeagle/pup#353]
I just tried testing this project locally and setup my `settings-development.js` as follows:

```json
{
  "public": {
    "graphQL": {
      "httpUri": "http://localhost:3000/graphql"
    },
    "productName": "Product Name",
    "copyrightStartYear": "2018",
    "twitterUsername": "product",
    "facebookUsername": "product",
    "productAddress": "1658 N. Milwaukee Ave., #393, Chicago, IL 60647"
  },
  "private": {
    "MAIL_URL": "",
    "OAuth": {
      "facebook": {
        "enabled": false,
        "appId": "",
        "secret": "",
        "loginStyle": "popup"
      },
      "google": {
        "enabled": false,
        "clientId": "",
        "secret": "",
        "loginStyle": "popup"
      },
      "github": {
        "enabled": false,
        "clientId": "",
        "secret": "",
        "loginStyle": "popup"
      }
    },
    "supportEmail": "Customer Support <support@product.com>"
  }
}
```

I cannot navigate to the Signup or login page, when I attempt to do this I get the following error:
```javascript
Uncaught TypeError: Cannot read property 'length' of undefined

The above error occurred in the <OAuthLoginButtons> component:
```
Is it possible to run this project with only email\password authentication?

Thanks.

**Comment by cleverbeagle** [comment]
@odesey, yes, it should work fine with email/password only. When you start your server up, make sure that you're passing this settings file with either `npm run dev` or `meteor --settings settings-development.json`.

If that doesn't work, let me know here.

**Comment by odesey** [comment]
Yes, i tried starting the app with the settings you mentioned, and got the same error mentioned in the initial issue.

**Comment by odesey** [comment]
1. Latest version, I ran the following command `git clone https://github.com/cleverbeagle/pup.git`
2. MacOS 10.15.7
3. `npm run dev`
4. Also tried upgrading Meteor with `meteor update` and got the same error

**Comment by odesey** [comment]
![Screen Shot 2021-03-02 at 12 04 44 PM](https://user-images.githubusercontent.com/3899366/109686295-239ca280-7b50-11eb-8eab-f2906f9e6926.png)

Added screenshot of error.

**Comment by rglover** [comment]
I see it. It looks like the port is being set as `4500` but the expectation of the default settings is that you're running the app on port `3000`. Are you running anything like `npm run dev --port 4500`?

**Comment by odesey** [comment]
So I was indeed running this on port 4500 but changing the following:
`"dev": "meteor --settings settings-development.json --port 4500"`

I had another server running on port 3000

Removing the `--port 4500` seems to have resolved the issue.

What other changes do I need to make in order to run pup on a port other than `3000`?

Thanks for the help!

**Comment by rglover** [comment]
Okay cool. If you *do* want to use a different port, just make sure to update the `public.graphQL.httpUri` in your settings file to use `:4500` (or whatever port you'd like) instead of `3000`.

**Comment by odesey** [comment]
Awesome, that works.

Thanks for your help!
