### ISSUE TITLE
Need help with checkboxes

### ISSUE THREAD

**Issue by jolesbi** [cleverbeagle/pup#36]
Thank you so much for open sourcing this boilerplate. I'm really enjoying it and am learning a lot. I'm fairly new when it comes to React and Meteor so my question may be very basic.

How would you recommend adding a `<Checkbox>` to `DocumentEditor.js` for example? 

I have a checkbox "working" with Meteor, but relying on `state` for the checkbox leaves the view out of sync when I refresh the page. `ref=` doesn't seem to work either as it does for other inputs on the form.

Thank you kindly!

**Comment by cleverbeagle** [comment]
Hi @jolesbi for refs on the `<Checkbox>` component from `react-bootstrap`, you will need to assign those via the prop `inputRef` instead of `ref` ([details available here](https://react-bootstrap.github.io/components.html#forms-props-checkbox)).

**Comment by leite08** [comment]
Did you make it to work @jolesbi ?
I'm trying to make checkbox work with no luck. Tried `<input type="checkbox">` with `onChange=".."` and `<Checkbox>` with `inputRef` set, but none works. Can't find an example of it working with the same setup of Pup (Meteor + React + Bootstrap).
If you did get it working, did you need to setup anything else besides `inputRef`? Can you share this piece of code?

Mine looks like this (enabled is a property of our domain object, "module"):
`<Checkbox inputRef={enabled => {this.enabled = enabled;}}/>`

As a reference, another element on the same form:
`<input type="text" className="form-control" name="description" ref={description => (this.description = description)} defaultValue={module && module.description}/>`

One weird thing is that, on the `handleSubmit()` method, calling `console.log(this.enabled.value)` outputs `on` (was expecting `true` or `checked`).

**Comment by leite08** [comment]
Managed to get the correct value from the checkbox with `this.enabled.checked` (was using the property `value` incorrectly).
Thanks!
