### ISSUE TITLE
Refactor form inputs to use React Bootstrap <FormControl /> with inputRef props

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#38]
This should help us to avoid bare inputs unless absolutely necessary.

**Comment by pilarArr** [comment]
Now that bootstrap v4 beta is out and v3 is no longer supported, we might want to wait a bit on this one to see if React Bootstraps brings out Bootstrap v4 support. Looks like the React-Bootstrap team might collaborate the reactstrap team to speed this up.

This are the related issues/PR/repositories:
- [React-Bootstrap](https://github.com/react-bootstrap/react-bootstrap)
- react-bootstrap/react-bootstrap/issues/1187
- react-bootstrap/react-bootstrap/pull/2752
- [reactstrap](https://github.com/reactstrap/reactstrap)

But if you don't want to wait I can look into it. 👌

**Comment by cleverbeagle** [comment]
I'm fine with waiting, this was just something that was a bit frustrating/inconsistent but nothing blocking. This ties into the Slack thread about a UI kit, which, answering your question there in here, yes, UI kit === Bootstrap. The goal would be to give us a bit more control over having to wait on stuff like this vs. just adding/changing things when we'd like.

**Comment by pilarArr** [comment]
I'm still not sure of what you'd like to accomplish:
- Do you want to make something like React Bootstrap but with the components we use/need so that we have control over keeping it up to date with the current Bootstrap version? 
- Or would you like to replace Bootstrap components altogether with a custom UI kit?

**Comment by cleverbeagle** [comment]
> Or would you like to replace Bootstrap components altogether with a custom UI kit?

This. My only hesitation is that it's a massive undertaking, and if it caught on outside of our customer base: a huge maintenance responsibility. Long-term, my thinking is to have a basic version of the kit and then have additional components available for sale.

More immediately, I'd rather stick with what we have—Bootstrap—and start to prototype our own UI kit on the side to see how much effort it would take (we'd also have to factor in browser compatibility which can be a chore).
