### ISSUE TITLE
Feature Request: Add Analytics

### ISSUE THREAD

**Issue by 416serg** [cleverbeagle/pup#39]
Wether it's through `okgrow:analytics` or `react-ga`, I am having difficulties setting it up with React Router v4 😢

**Comment by cleverbeagle** [comment]
Hey @416serg, this is on the list :) May end up in Pup Pro, though.

**Comment by ninjaPixel** [comment]
I this an issue specifically with react-router?

In the long run, I think that integrating [Google Tag Manager](https://www.google.com/analytics/tag-manager/) would be a good general solution for user tracking.
GTM enables us to hook up to lots of different analytics providers (e.g. Google Analytics, Hotjar etc etc) without having to redeploy our app.
We'd just need to inject 2 GTM scripts in the HTML and then call tracking events from the `.js` (e.g. on route change events and any other custom events like button clicks, page scrolling etc).

**Comment by cleverbeagle** [comment]
This is a big sticky problem 😈

Ideally we could find a balance between the point-and-click tracking services and something more programmatic (I've found scenarios where both are ideal). Of note, support for [Segment](https://segment.com/) is what came to mind as they push data to nearly everything. They're paid, but the bulk of our customers will likely fall into their developer plan tier which is free for up to 1,000 tracked users.

Most importantly: ease-of-use and understanding. Our primary focus is always on beginners so we want to avoid making any assumptions about what's easy (read: it may be easy to _us_ but not to someone who is totally green to this stuff).

**Comment by ninjaPixel** [comment]
Segment do have a nice API 👍 

FYI Astronomer is free for 1M events per month and uses the same API. It's what we used in the [split testing](https://themeteorchef.com/tutorials/split-testing-with-meteor) tutorial.

Either of the above would be excellent solutions.

**Comment by cleverbeagle** [comment]
Ah, right. Astronomer would be great! It's got a nice historical tie back to Meteor and we may be able to collab with the folks over there.

**Comment by 416serg** [comment]
I am in the process of setting up [okgrow:auto-analytics](https://github.com/okgrow/auto-analytics) with `react-helmet`. It's working with Segment however just working through `react-helmet` to make sure the right `analytics.whatever` calls get tracked because it's a little tougher to set up with `react-router@4.*`
