### ISSUE TITLE
Make logout happen on logout page

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#40]
Right now the logout page is just a stylized way to promote something to users on logout. It'd be neat if this page actually performed the logout event on `componentDidMount()`. This way we could redirect to that page (without having it do so in the `<Authenticated />` component) directly while also getting the desired outcome of logging out.

**Comment by pilarArr** [comment]
There is this bug related to the logout page. When you log out from the home page `/`, it looks like you don't go through the logout page, unless it's done lightning fast.
![logoutbug mov](https://user-images.githubusercontent.com/26302137/30102026-9e15803e-92ee-11e7-8616-fea5d34b45a5.gif)

**Comment by cleverbeagle** [comment]
Ah, yes. We'd need to double check all of the redirects in the app and avoid direct calls to `Meteor.logout()` otherwise this could get messy.
