### ISSUE TITLE
Throw Exception from actions always return same error code

### ISSUE THREAD

**Issue by tafelito** [cleverbeagle/pup#48]
Hi, when creating an action within a meteor method, if you throw an Meteor.Error with a custom code, when you catch from the client, the error code is always 500 because the catch on the method always return 500

```js
} catch((exception) => {
  throw new Meteor.Error('500', exception);
});
```

I changed it on my code, but I though it was a good idea to adjust it here as well

Thanks

**Comment by tafelito** [comment]
Btw, what's the best way to share actions through different methods. Let's say you have a meteor method that has 3 steps (actions) and then there is another method that needs to call 1 of the same actions, do you take it out to a different file and then export it? Do you put it within the imports/api or you put it on import/modules? Do you pass the promise through in case you need to reject it if an error happens?

Thanks

**Comment by cleverbeagle** [comment]
Hi @tafelito customizing the error code in your own is best. The `500` is generic enough to alert that something went wrong on the server. Is the change you're proposing to pass the full `exception` to the client?

Re: sharing actions, this depends. You can do an `export const` of a specific method inside of an action, or, if it's something a bit more complex, just take that code and put it in its own file, importing it into both the action and the method. Both work but it's really a judgment call based on the work you're doing/how often the code will be reused.

**Comment by tafelito** [comment]
thanks @cleverbeagle for the answer. What I meant by customizing the error code is that when you throw an Meteor.Error from an action, then you are catching it on the method and throwing a new Meteor.Error with error code 500, so the cliente always get 500, not the one thrown in a specific action. Not sure If I'm being clear here

So if I have this
```js
const action1 = ({ ... }) => {
  try {
    throw new Meteor.Error('600', 'Error msg');
  } catch (exception) {
    action.reject(`[handler.action1] ${exception}`);
  }
};

const handler = ({ ... }, promise) => {
  try {
    action = promise;

    action1(...);
    action2(...); //this will be executed 
    action.resolve();
  } catch (exception) {
    action.reject(`[handler] ${exception}`);
  }
};

Meteor.methods({
  method(...) {
    return handler({ ... })
      .then(response => response)
      .catch((exception) => {
       throw new Meteor.Error('500', exception); // always returns error code 500, not 600
      });
  },
});
```

So right now, instead of sending the message from the reject, I return an object, with the message, and the exception itself and then in the catch I do this

```js
  .catch(({ exception, message }) => {
    throw new Meteor.Error(exception.error, message);
  });
```

It should have an extra validation though, in case the exception is not an actual Meteor.Error
