### ISSUE TITLE
integrating a datepicker how to

### ISSUE THREAD

**Issue by jsaddiction** [cleverbeagle/pup#58]
I am trying to implement [this datepicker](https://github.com/Hacker0x01/react-datepicker) into the `EditDocuments.js` i have setup the schema, api and i have imported the component/stylesheet and `moment.js`.  So far I have successfully rendered the datepicker into the page and populated the date saved in mongo by adding 
`
 <FormGroup>
        <ControlLabel>Due Date</ControlLabel>
        <DatePicker
          className="form-control"
          selected={moment(this.props.dueDate)}
          onChange={this.handleChange}
        />
      </FormGroup>
`

the `handleChange` looks like

`
handleChange(date) {
    this.setState({
      dueDate : date
    })
  }
`

I am currently getting an error "this.setState() is not a function" even though i have 

`this.handleChange = this.handleChange.bind(this);`

 in the `componentDidMount()` function.

This is mainly caused by the fact that i am not familiar with react but most tutorials do not implement react as it is done here.  I appreciate any help in advance!!

**Comment by cleverbeagle** [comment]
Hey, @jsaddiction :) Would you mind moving this to [http://forum.cleverbeagle.com/](http://forum.cleverbeagle.com/) for us? We're looking to move general/non-bug related issues over there.
