### ISSUE TITLE
esLint goes crazy on Windows with CRLF rule

### ISSUE THREAD

**Issue by pilarArr** [cleverbeagle/pup#59]
It's the [linebreak-style](https://eslint.org/docs/rules/linebreak-style) rule, they have a tip on that page as to how to fix it.

The matter is that `git` on Windows when it does the checkout it replaces all linebreaks from LF to CRLF, then again when you check the changes it does the inverse operation. `git` does this to ensure consistency on line breaks. At least that's what I understood that happens. 

So if you don't use a linter, you don't notice this and it does affect you at all.
The problem is that this linter rule, checks for the linebreak and throws an error for all these line breaks and when you save the file in Atom it automatically does the fix and `git` registers that as a change in the file that you have to commit again. I did get to test what would happen if I actually went and committed the file (maybe it wont let me) but they suggest two ways around this:

1. Changing the rule to allow both line breaks or disable it, but it doesn't feel right because then you could end up with mixed line breaks. But maybe we don't care about that.
1. Or setting up a `gitattributes` file that would prevent `git` from doing that linebreak change on `.js` files.

**Comment by cleverbeagle** [comment]
What is the CRLF rule?

**Comment by pilarArr** [comment]
@cleverbeagle updated the issue description

**Comment by cleverbeagle** [comment]
So in other words some people just like to watch the world burn? :p

Okay, then yes. I'd agree with what you're saying here and compromise with the `gitattributes` file. Going to queue this up as a chore. Happy to take it if you don't want to.

**Comment by pilarArr** [comment]
I already have it. I had to do it today for another project since we had a windows laptop joining the team and hell almost broke loose.

**Comment by cleverbeagle** [comment]
Hahaha right on 👍
