### ISSUE TITLE
Remove jQuery 2.X from dependencies

### ISSUE THREAD

**Issue by ninjaPixel** [cleverbeagle/pup#64]
Using the bundle visualizer you can see that `jQuery` is imported twice. Once by Meteor and again in the npm dependencies. Unless we need  2 different versions of `jQuery`, we might as well remove the npm one (85.9kB).

Meteor bundles up version`1.11.10`, version `2.2.4` is specified in `package.json`. I don't think there would be any issue in ditching 2.X as I believe the API is identical, it's just that 2.X doesn't support IE 6-8.

@pilarArr Are you aware of anything that would break if we ditch `jQuery 2.X`?

FYI run bundle visualizer like so:
```
meteor add bundle-visualizer
meteor --production --settings settings-development.json
```
Once you've finished, remember to do
```
meteor remove bundle-visualizer
```

**Comment by pilarArr** [comment]
@ninjaPixel That I know of, `ttwbs:bootstrap` and `jquery-validation` both have dependecies on `jquery`. Bootstrap broke when I updated `jquery` to v3,  but I think it should be all right if we downgrade.

Also the file in the module `/imports/modules/validate` uses `jquery` from `npm`, that would be also easy to change. And I think that's it.

**Comment by pilarArr** [comment]
Can we delete the`jquery` that meteor installs?

**Comment by ninjaPixel** [comment]
Thanks for testing this @pilarArr 

> Can we delete the `jquery` that meteor installs?

The `blaze` package depends on the `jQuery` package, so it'd depend on how much stuff needs  `blaze`. I'm not that familiar with the repo just yet, but I'd guess that quite a lot of packages need `blaze`.

**Comment by pilarArr** [comment]
>The `blaze` package depends on the `jQuery` package, so it'd depend on how much stuff needs `blaze`. I'm not that familiar with the repo just yet, but I'd guess that quite a lot of packages need `blaze`.

I'm not that sure about this, as far as I understand `blaze` is what Meteor uses to make the UI, but we use React in Pup to do that, so it should be safe to delete the `blaze` templates libraries since we don't use them. Maybe @cleverbeagle has more info about this.

**Comment by cleverbeagle** [comment]
@pilarArr we'd need to keep the Meteor version of Blaze because of what @ninjaPixel is saying here. We don't use Blaze directly in Pup, but some of the packages we depend on (for example, `themeteorchef:bert`) _do_ depend on Blaze and by extension Meteor's copy of jQuery. I'd say the safe bet would be to drop the NPM version but avoid tinkering with the Meteor copy.

**Comment by cleverbeagle** [comment]
Thinking a bit further, too, it may be worth doing an audit to see which packages depend on jQuery so we can start to phase them out (or if they're something in our control, bring them up to date).

**Comment by pilarArr** [comment]
I think that ditching NPM's jQuery version is not going to be that easy. I'll do some more testing.
