### ISSUE TITLE
SSR (w/ metadata via React Helmet)

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#69]
This turned on a few lightbulbs and has me interested in getting this working in an upcoming release (perhaps 1.3/1.4?): https://blog.meteor.com/meteor-platform-is-still-alive-5f6426644555. Would also be worth it to take a leaf from this implementation and add support for React Helmet and SEO tags by default. 

Ideally, we could get this packed up into a single wrapper component/module so folks don't have to muck with Redux or anything like that—just wrap their existing code and go.

**Comment by ninjaPixel** [comment]
Just curious, given that our clients would generally deploy to Galaxy (am I right here), why not just rely on the free Prerender integration? http://galaxy-guide.meteor.com/seo.html

**Comment by cleverbeagle** [comment]
You're right, but I'd like us to be less reliant on Galaxy as a deployment option (e.g., a few folks have used Heroku recently for costs). That and I've found Prerender can get "stuck" sometimes, with data being cached making updates harder to do. It'd be nice to know that SEO support is just built-in and doesn't require using a specific host.
