### ISSUE TITLE
URI malformed when sending emails

### ISSUE THREAD

**Issue by 416serg** [cleverbeagle/pup#70]
After configuring `MAIL_URL`, when I sign up a new user I get the following error

```
Exception in defer callback: URIError: URI malformed
     at decodeURIComponent (native)
     at Url.parse (url.js:195:19)
     at Object.urlParse [as parse] (url.js:84:5)
     at makeTransport (packages/email.js:42:27)
     at getTransport (packages/email.js:78:24)
     at Object.Email.send (packages/email.js:172:19)
     at imports/modules/server/send-email.js:8:30
     at [object Object].EVp.withValue (packages/meteor.js:1134:15)
     at packages/meteor.js:452:25
     at runWithEnvironment (packages/meteor.js:1188:24)
```

Most recent version of `Pup` - just cloned, added `MAIL_URL` in `settings-development.json`, ran `npm start` and tried to sign up.

I tracked it down to the error happening within [Send Email module](https://github.com/cleverbeagle/pup/blob/master/imports/modules/server/send-email.js) but not sure how to fix it.

Should I try `meteorhacks:ssr` instead of `handlebars` to generate the email content or hopefully you know of a workaround

**Comment by cleverbeagle** [comment]
What is the error you're getting from the `send-email.js` module? Is it related to #66?

**Comment by 416serg** [comment]
Not getting any more errors, just the one above on the server. Only reason I said `send-email.js` was the issue is because the error happens when `sendWelcomeEmail` happens which calls `sendEmail` -> Could it be that the HTML content of that email is messed up?

**Comment by 416serg** [comment]
I am a total idiot - my `MAIL_URL` was wrong 😓
