### ISSUE TITLE
Migrate @cleverbeagle/dates to /imports/modules

### ISSUE THREAD

**Issue by cleverbeagle** [cleverbeagle/pup#78]
This is currently an NPM package but it's wreaking more havoc than necessary. We should move this into the `/imports/modules` directory as `dates.js`. Same exact code, just drop the package/need for extra maintenance.

**Comment by tomscholz** [comment]
I can take this one. Just one question: What about the tests? In pup there aren't any, but inside the npm package there are.

**Comment by cleverbeagle** [comment]
@tomscholz hey, Tom. Thanks for your interest in this. Work on Pup is going to remain strictly internal as our mentors rely on it for working with customers. That said, if you're interested in working on the kit, send me an email: ryan.glover@cleverbeagle.com.
