### ISSUE TITLE
Minimise lodash footprint

### ISSUE THREAD

**Issue by ninjaPixel** [cleverbeagle/pup#79]
Use [this Babel plugin](https://github.com/lodash/babel-plugin-lodash) which will make sure that only the lodash functions that we use are included in the client bundle. It'll save over 70kB from the bundle size.

**Comment by ninjaPixel** [comment]
I've implemented this and it's dropped the size of the lodash module to just 3.38kB
Bundle pic: https://www.dropbox.com/s/dyd140nhst0ja4t/Screenshot%202017-10-16%2017.18.28.png?dl=0

**Comment by cleverbeagle** [comment]
Woah! Nice work, sir.
