### ISSUE TITLE
throw new Meteor.Error('500', exception) when exception is already a Meteor Error

### ISSUE THREAD

**Issue by jrios6** [cleverbeagle/pup#87]
In Documents methods.js try-catch statement, the exception (from violating simple schema) is already a Meteor.Error, yet it's used as a parameter for throwing new exception. 

The result is that the client is not able to render the Bert alert.

Can you clarify other than from violating the schema, would there be any other reasons for an exception?

**Comment by cleverbeagle** [comment]
As the code exists now in Pup, no. However, the try/catch block is a good pattern to implement across all Meteor Methods to handle error handling (especially if the code inside the Method is doing work beyond database writes).

**Comment by jrios6** [comment]
Thanks! So is it safe to assume currently it will be fine to replace  `throw new Meteor.Error('500', exception)` with just `throw exception`?

**Comment by zeiitoun** [comment]
I would rather specify a new Meteor Error for production mode. Something like "Meteor.Error('500', 'There was an error during the insertion of the document')"

Violation of the simple schema will be the result of a client modification (if you did your form properly). The "hacker" doesn't need a personalized error message. 

During dev mode, you can log the error if you need more information.

**Comment by cleverbeagle** [comment]
Agree with @zeiitoun here. Also, @jrios6 keep in mind that `Meteor.Error()` ensures the error bubbles back up from the Method call to the client:

> Methods can throw any kind of exception. But Meteor.Error is the only kind of error that a server will send to the client.
>
> – [Meteor.Error](https://docs.meteor.com/api/methods.html#Meteor-Error) in Meteor docs
