### ISSUE TITLE
Where do I edit meta tags etc in the <head>?

### ISSUE THREAD

**Issue by Bandit** [cleverbeagle/pup#88]
I'm sure this is super obvious but I can't find it anywhere.

Looking to install a [Bootstrap theme](https://atmospherejs.com/fezvrasta/bootstrap-material-design). Also how do I include JS before `</body>`?

**Comment by Bandit** [comment]
Found it `/client/main.html` 👍 

Still want to know the correct way to append JS files from a package

**Comment by cleverbeagle** [comment]
@Bandit depends on what you're trying to append from the package. If it's a Bootstrap theme, can you share a sample of the files they're asking you to load?

**Comment by Bandit** [comment]
Sorry for my lack of response on this - haven't had a chance to get back to this project yet.
