### ISSUE TITLE
Use process.env in config

### ISSUE THREAD

**Issue by Ghalleb** [cleverbeagle/pup#97]
Hi,

I think it would be a good idea to use "process.env" for all config settings.
First because you don't want to store private information in the code and second because it would be easier to use on platform like heroku. 

I know it's just a 'settings-development' file and not the real production file, but as it could be used as example, it could be helpfull.

Example:

    {
      "public": {},
      "private": {
        "MAIL_URL": "",
        "OAuth": {
          "facebook": {
            "appId": process.env.FACEBOOK_ID || 'FACEBOOK_ID',
            "secret": process.env.FACEBOOK_SECRET || 'FACEBOOK_SECRET',
            "loginStyle": "popup"
          },
        }
      }
    }

**Comment by Ghalleb** [comment]
My solution is to use a var and change it state on touch events. Then use it in the click event:

    var dragged = false;

    google.maps.event.addListener(map, 'click', function (evt) {
        if (!dragged) {
            // Do stuff here
        }
    });

    google.maps.event.addDomListener(canvas, 'touchmove', function (event) {
        if (event.touches.length == 1) {
            dragged = true;
        }
    });

    google.maps.event.addDomListener(canvas, 'touchend', function(event) {
        dragged = false;
    });

**Comment by cleverbeagle** [comment]
Hi @Ghalleb. This isn't something we'll likely include as we'd expect the contents of your settings file to be passed to your host, or, to manage any environment variables manually via their dashboard. Technically, even though we store things in this file, it's loaded by Meteor as `process.env.METEOR_SETTINGS`. The `Meteor.settings` helper in the app just loads from the contents of that file.

What does Heroku require you to do in respect to setting your environment variables (not familiar with it)?

**Comment by Ghalleb** [comment]
Heroku use a list of key/value.
So I guess I could simply use a configuration like:
METEOR_SETTINGS -> "my json configuration".
That should do the trick.
